//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3623
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataPackageTestClient.DataPackageClientService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataTypeErrorPlusBaselineDefinitionList", Namespace="http://schemas.datacontract.org/2004/07/DataPackage")]
    [System.SerializableAttribute()]
    public partial class DataTypeErrorPlusBaselineDefinitionList : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DataPackageTestClient.DataPackageClientService.BaselineDefinition[] baselineDefField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DataPackageTestClient.DataPackageClientService.DataPackageErrorEnum error_codeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DataPackageTestClient.DataPackageClientService.BaselineDefinition[] baselineDef {
            get {
                return this.baselineDefField;
            }
            set {
                if ((object.ReferenceEquals(this.baselineDefField, value) != true)) {
                    this.baselineDefField = value;
                    this.RaisePropertyChanged("baselineDef");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DataPackageTestClient.DataPackageClientService.DataPackageErrorEnum error_code {
            get {
                return this.error_codeField;
            }
            set {
                if ((this.error_codeField.Equals(value) != true)) {
                    this.error_codeField = value;
                    this.RaisePropertyChanged("error_code");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaselineDefinition", Namespace="http://schemas.datacontract.org/2004/07/DataPackage")]
    [System.SerializableAttribute()]
    public partial class BaselineDefinition : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime BaselineCreationDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BaselineDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BaselineVersionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LMTDataPackageVersionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PISBaseDataPackageVersionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PISInfotainmentDataPackageVersionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PISMissionDataPackageVersionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime BaselineCreationDate {
            get {
                return this.BaselineCreationDateField;
            }
            set {
                if ((this.BaselineCreationDateField.Equals(value) != true)) {
                    this.BaselineCreationDateField = value;
                    this.RaisePropertyChanged("BaselineCreationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BaselineDescription {
            get {
                return this.BaselineDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.BaselineDescriptionField, value) != true)) {
                    this.BaselineDescriptionField = value;
                    this.RaisePropertyChanged("BaselineDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BaselineVersion {
            get {
                return this.BaselineVersionField;
            }
            set {
                if ((object.ReferenceEquals(this.BaselineVersionField, value) != true)) {
                    this.BaselineVersionField = value;
                    this.RaisePropertyChanged("BaselineVersion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LMTDataPackageVersion {
            get {
                return this.LMTDataPackageVersionField;
            }
            set {
                if ((object.ReferenceEquals(this.LMTDataPackageVersionField, value) != true)) {
                    this.LMTDataPackageVersionField = value;
                    this.RaisePropertyChanged("LMTDataPackageVersion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PISBaseDataPackageVersion {
            get {
                return this.PISBaseDataPackageVersionField;
            }
            set {
                if ((object.ReferenceEquals(this.PISBaseDataPackageVersionField, value) != true)) {
                    this.PISBaseDataPackageVersionField = value;
                    this.RaisePropertyChanged("PISBaseDataPackageVersion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PISInfotainmentDataPackageVersion {
            get {
                return this.PISInfotainmentDataPackageVersionField;
            }
            set {
                if ((object.ReferenceEquals(this.PISInfotainmentDataPackageVersionField, value) != true)) {
                    this.PISInfotainmentDataPackageVersionField = value;
                    this.RaisePropertyChanged("PISInfotainmentDataPackageVersion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PISMissionDataPackageVersion {
            get {
                return this.PISMissionDataPackageVersionField;
            }
            set {
                if ((object.ReferenceEquals(this.PISMissionDataPackageVersionField, value) != true)) {
                    this.PISMissionDataPackageVersionField = value;
                    this.RaisePropertyChanged("PISMissionDataPackageVersion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataPackageErrorEnum", Namespace="http://schemas.datacontract.org/2004/07/DataPackage")]
    public enum DataPackageErrorEnum : uint {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OK = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BAD_SESSION_ID = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ERROR = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        INVALID_BASELINE_VERSION = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        INVALID_PIS_BASE_DATA_PACKAGE_VERSION = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        INVALID_PIS_MISSION_DATA_PACKAGE_VERSION = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        INVALID_PIS_INFOTAINMENT_DATA_PACKAGE_VERSION = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        INVALID_LMT_DATA_PACKAGE_VERSION = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ELEMENT_ID_NOT_FOUND = 20,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        INVALID_MISSION_ID = 21,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        INCOHERENT_EXPIRATION_DATEANDTIME = 30,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FILE_NOT_FOUND = 40,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        INVALID_PATH = 41,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        INVALID_TRANSFER_MODE = 50,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        INVALID_TIMEOUT = 51,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TargetAddressType", Namespace="http://alstom.com/pacis/pis/schema/")]
    [System.SerializableAttribute()]
    public partial class TargetAddressType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DataPackageTestClient.DataPackageClientService.AddressTypeEnum TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DataPackageTestClient.DataPackageClientService.AddressTypeEnum Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddressTypeEnum", Namespace="http://alstom.com/pacis/pis/schema/")]
    public enum AddressTypeEnum : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Element = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MissionOperatorCode = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MissionCommercialNumber = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataTypeErrorPlusElementDescriptionList", Namespace="http://schemas.datacontract.org/2004/07/DataPackage")]
    [System.SerializableAttribute()]
    public partial class DataTypeErrorPlusElementDescriptionList : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DataPackageTestClient.DataPackageClientService.ElementDescription[] ElementDescField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DataPackageTestClient.DataPackageClientService.DataPackageErrorEnum error_codeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DataPackageTestClient.DataPackageClientService.ElementDescription[] ElementDesc {
            get {
                return this.ElementDescField;
            }
            set {
                if ((object.ReferenceEquals(this.ElementDescField, value) != true)) {
                    this.ElementDescField = value;
                    this.RaisePropertyChanged("ElementDesc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DataPackageTestClient.DataPackageClientService.DataPackageErrorEnum error_code {
            get {
                return this.error_codeField;
            }
            set {
                if ((this.error_codeField.Equals(value) != true)) {
                    this.error_codeField = value;
                    this.RaisePropertyChanged("error_code");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ElementDescription", Namespace="http://schemas.datacontract.org/2004/07/DataPackage")]
    [System.SerializableAttribute()]
    public partial class ElementDescription : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AssignedCurrentBaselineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime AssignedCurrentBaselineExpirationDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AssignedFutureBaselineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime AssignedFutureBaselineActivationDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime AssignedFutureBaselineExpirationDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DataPackageTestClient.DataPackageClientService.ElementBaseline ElementArchivedBaselineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ElementArchivedBaselineExpirationDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DataPackageTestClient.DataPackageClientService.ElementBaseline ElementCurrentBaselineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ElementCurrentBaselineExpirationDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DataPackageTestClient.DataPackageClientService.ElementBaseline ElementFutureBaselineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ElementFutureBaselineActivationDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ElementFutureBaselineExpirationDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ElementIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool isCurrentBaselineForcedField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AssignedCurrentBaseline {
            get {
                return this.AssignedCurrentBaselineField;
            }
            set {
                if ((object.ReferenceEquals(this.AssignedCurrentBaselineField, value) != true)) {
                    this.AssignedCurrentBaselineField = value;
                    this.RaisePropertyChanged("AssignedCurrentBaseline");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime AssignedCurrentBaselineExpirationDate {
            get {
                return this.AssignedCurrentBaselineExpirationDateField;
            }
            set {
                if ((this.AssignedCurrentBaselineExpirationDateField.Equals(value) != true)) {
                    this.AssignedCurrentBaselineExpirationDateField = value;
                    this.RaisePropertyChanged("AssignedCurrentBaselineExpirationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AssignedFutureBaseline {
            get {
                return this.AssignedFutureBaselineField;
            }
            set {
                if ((object.ReferenceEquals(this.AssignedFutureBaselineField, value) != true)) {
                    this.AssignedFutureBaselineField = value;
                    this.RaisePropertyChanged("AssignedFutureBaseline");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime AssignedFutureBaselineActivationDate {
            get {
                return this.AssignedFutureBaselineActivationDateField;
            }
            set {
                if ((this.AssignedFutureBaselineActivationDateField.Equals(value) != true)) {
                    this.AssignedFutureBaselineActivationDateField = value;
                    this.RaisePropertyChanged("AssignedFutureBaselineActivationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime AssignedFutureBaselineExpirationDate {
            get {
                return this.AssignedFutureBaselineExpirationDateField;
            }
            set {
                if ((this.AssignedFutureBaselineExpirationDateField.Equals(value) != true)) {
                    this.AssignedFutureBaselineExpirationDateField = value;
                    this.RaisePropertyChanged("AssignedFutureBaselineExpirationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DataPackageTestClient.DataPackageClientService.ElementBaseline ElementArchivedBaseline {
            get {
                return this.ElementArchivedBaselineField;
            }
            set {
                if ((object.ReferenceEquals(this.ElementArchivedBaselineField, value) != true)) {
                    this.ElementArchivedBaselineField = value;
                    this.RaisePropertyChanged("ElementArchivedBaseline");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ElementArchivedBaselineExpirationDate {
            get {
                return this.ElementArchivedBaselineExpirationDateField;
            }
            set {
                if ((this.ElementArchivedBaselineExpirationDateField.Equals(value) != true)) {
                    this.ElementArchivedBaselineExpirationDateField = value;
                    this.RaisePropertyChanged("ElementArchivedBaselineExpirationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DataPackageTestClient.DataPackageClientService.ElementBaseline ElementCurrentBaseline {
            get {
                return this.ElementCurrentBaselineField;
            }
            set {
                if ((object.ReferenceEquals(this.ElementCurrentBaselineField, value) != true)) {
                    this.ElementCurrentBaselineField = value;
                    this.RaisePropertyChanged("ElementCurrentBaseline");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ElementCurrentBaselineExpirationDate {
            get {
                return this.ElementCurrentBaselineExpirationDateField;
            }
            set {
                if ((this.ElementCurrentBaselineExpirationDateField.Equals(value) != true)) {
                    this.ElementCurrentBaselineExpirationDateField = value;
                    this.RaisePropertyChanged("ElementCurrentBaselineExpirationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DataPackageTestClient.DataPackageClientService.ElementBaseline ElementFutureBaseline {
            get {
                return this.ElementFutureBaselineField;
            }
            set {
                if ((object.ReferenceEquals(this.ElementFutureBaselineField, value) != true)) {
                    this.ElementFutureBaselineField = value;
                    this.RaisePropertyChanged("ElementFutureBaseline");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ElementFutureBaselineActivationDate {
            get {
                return this.ElementFutureBaselineActivationDateField;
            }
            set {
                if ((this.ElementFutureBaselineActivationDateField.Equals(value) != true)) {
                    this.ElementFutureBaselineActivationDateField = value;
                    this.RaisePropertyChanged("ElementFutureBaselineActivationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ElementFutureBaselineExpirationDate {
            get {
                return this.ElementFutureBaselineExpirationDateField;
            }
            set {
                if ((this.ElementFutureBaselineExpirationDateField.Equals(value) != true)) {
                    this.ElementFutureBaselineExpirationDateField = value;
                    this.RaisePropertyChanged("ElementFutureBaselineExpirationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ElementID {
            get {
                return this.ElementIDField;
            }
            set {
                if ((object.ReferenceEquals(this.ElementIDField, value) != true)) {
                    this.ElementIDField = value;
                    this.RaisePropertyChanged("ElementID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isCurrentBaselineForced {
            get {
                return this.isCurrentBaselineForcedField;
            }
            set {
                if ((this.isCurrentBaselineForcedField.Equals(value) != true)) {
                    this.isCurrentBaselineForcedField = value;
                    this.RaisePropertyChanged("isCurrentBaselineForced");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ElementBaseline", Namespace="http://schemas.datacontract.org/2004/07/DataPackage")]
    [System.SerializableAttribute()]
    public partial class ElementBaseline : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BaselineValidityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BaselineVersionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool LMTDataPackageValidityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LMTDataPackageVersionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool PISBaseDataPackageValidityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PISBaseDataPackageVersionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool PISInfotainmentDataPackageValidityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PISInfotainmentDataPackageVersionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool PISMissionDataPackageValidityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PISMissionDataPackageVersionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BaselineValidity {
            get {
                return this.BaselineValidityField;
            }
            set {
                if ((this.BaselineValidityField.Equals(value) != true)) {
                    this.BaselineValidityField = value;
                    this.RaisePropertyChanged("BaselineValidity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BaselineVersion {
            get {
                return this.BaselineVersionField;
            }
            set {
                if ((object.ReferenceEquals(this.BaselineVersionField, value) != true)) {
                    this.BaselineVersionField = value;
                    this.RaisePropertyChanged("BaselineVersion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool LMTDataPackageValidity {
            get {
                return this.LMTDataPackageValidityField;
            }
            set {
                if ((this.LMTDataPackageValidityField.Equals(value) != true)) {
                    this.LMTDataPackageValidityField = value;
                    this.RaisePropertyChanged("LMTDataPackageValidity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LMTDataPackageVersion {
            get {
                return this.LMTDataPackageVersionField;
            }
            set {
                if ((object.ReferenceEquals(this.LMTDataPackageVersionField, value) != true)) {
                    this.LMTDataPackageVersionField = value;
                    this.RaisePropertyChanged("LMTDataPackageVersion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool PISBaseDataPackageValidity {
            get {
                return this.PISBaseDataPackageValidityField;
            }
            set {
                if ((this.PISBaseDataPackageValidityField.Equals(value) != true)) {
                    this.PISBaseDataPackageValidityField = value;
                    this.RaisePropertyChanged("PISBaseDataPackageValidity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PISBaseDataPackageVersion {
            get {
                return this.PISBaseDataPackageVersionField;
            }
            set {
                if ((object.ReferenceEquals(this.PISBaseDataPackageVersionField, value) != true)) {
                    this.PISBaseDataPackageVersionField = value;
                    this.RaisePropertyChanged("PISBaseDataPackageVersion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool PISInfotainmentDataPackageValidity {
            get {
                return this.PISInfotainmentDataPackageValidityField;
            }
            set {
                if ((this.PISInfotainmentDataPackageValidityField.Equals(value) != true)) {
                    this.PISInfotainmentDataPackageValidityField = value;
                    this.RaisePropertyChanged("PISInfotainmentDataPackageValidity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PISInfotainmentDataPackageVersion {
            get {
                return this.PISInfotainmentDataPackageVersionField;
            }
            set {
                if ((object.ReferenceEquals(this.PISInfotainmentDataPackageVersionField, value) != true)) {
                    this.PISInfotainmentDataPackageVersionField = value;
                    this.RaisePropertyChanged("PISInfotainmentDataPackageVersion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool PISMissionDataPackageValidity {
            get {
                return this.PISMissionDataPackageValidityField;
            }
            set {
                if ((this.PISMissionDataPackageValidityField.Equals(value) != true)) {
                    this.PISMissionDataPackageValidityField = value;
                    this.RaisePropertyChanged("PISMissionDataPackageValidity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PISMissionDataPackageVersion {
            get {
                return this.PISMissionDataPackageVersionField;
            }
            set {
                if ((object.ReferenceEquals(this.PISMissionDataPackageVersionField, value) != true)) {
                    this.PISMissionDataPackageVersionField = value;
                    this.RaisePropertyChanged("PISMissionDataPackageVersion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataTypeErrorPlusReqId", Namespace="http://schemas.datacontract.org/2004/07/DataPackage")]
    [System.SerializableAttribute()]
    public partial class DataTypeErrorPlusReqId : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DataPackageTestClient.DataPackageClientService.DataPackageErrorEnum error_codeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid reqIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DataPackageTestClient.DataPackageClientService.DataPackageErrorEnum error_code {
            get {
                return this.error_codeField;
            }
            set {
                if ((this.error_codeField.Equals(value) != true)) {
                    this.error_codeField = value;
                    this.RaisePropertyChanged("error_code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid reqId {
            get {
                return this.reqIdField;
            }
            set {
                if ((this.reqIdField.Equals(value) != true)) {
                    this.reqIdField = value;
                    this.RaisePropertyChanged("reqId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaselineDistributionAttributes", Namespace="http://schemas.datacontract.org/2004/07/DataPackage")]
    [System.SerializableAttribute()]
    public partial class BaselineDistributionAttributes : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DataPackageTestClient.DataPackageClientService.TransferModeEnum TransferModeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool fileCompressionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int priorityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime transferDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DataPackageTestClient.DataPackageClientService.TransferModeEnum TransferMode {
            get {
                return this.TransferModeField;
            }
            set {
                if ((this.TransferModeField.Equals(value) != true)) {
                    this.TransferModeField = value;
                    this.RaisePropertyChanged("TransferMode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool fileCompression {
            get {
                return this.fileCompressionField;
            }
            set {
                if ((this.fileCompressionField.Equals(value) != true)) {
                    this.fileCompressionField = value;
                    this.RaisePropertyChanged("fileCompression");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int priority {
            get {
                return this.priorityField;
            }
            set {
                if ((this.priorityField.Equals(value) != true)) {
                    this.priorityField = value;
                    this.RaisePropertyChanged("priority");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime transferDate {
            get {
                return this.transferDateField;
            }
            set {
                if ((this.transferDateField.Equals(value) != true)) {
                    this.transferDateField = value;
                    this.RaisePropertyChanged("transferDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TransferModeEnum", Namespace="http://schemas.datacontract.org/2004/07/DataPackage")]
    public enum TransferModeEnum : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        lowRate = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        highRate = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:DataPackage", ConfigurationName="DataPackageClientService.IDataPackageService")]
    public interface IDataPackageService {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:DataPackage/IDataPackageService/getBaselinesList", ReplyAction="urn:DataPackage/IDataPackageService/getBaselinesListResponse")]
        DataPackageTestClient.DataPackageClientService.DataTypeErrorPlusBaselineDefinitionList getBaselinesList(System.Guid pSessionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:DataPackage/IDataPackageService/getAddresseesDataPackagesBaselines", ReplyAction="urn:DataPackage/IDataPackageService/getAddresseesDataPackagesBaselinesResponse")]
        DataPackageTestClient.DataPackageClientService.DataTypeErrorPlusElementDescriptionList getAddresseesDataPackagesBaselines(System.Guid pSessionId, DataPackageTestClient.DataPackageClientService.TargetAddressType pElementAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:DataPackage/IDataPackageService/uploadDataPackages", ReplyAction="urn:DataPackage/IDataPackageService/uploadDataPackagesResponse")]
        DataPackageTestClient.DataPackageClientService.DataTypeErrorPlusReqId uploadDataPackages(System.Guid pSessionId, string[] pFilesURLs);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:DataPackage/IDataPackageService/defineNewBaseline", ReplyAction="urn:DataPackage/IDataPackageService/defineNewBaselineResponse")]
        DataPackageTestClient.DataPackageClientService.DataTypeErrorPlusReqId defineNewBaseline(System.Guid pSessionId, DataPackageTestClient.DataPackageClientService.BaselineDefinition pBLDef);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:DataPackage/IDataPackageService/assignFutureBaselineToElement", ReplyAction="urn:DataPackage/IDataPackageService/assignFutureBaselineToElementResponse")]
        DataPackageTestClient.DataPackageClientService.DataTypeErrorPlusReqId assignFutureBaselineToElement(System.Guid pSessionId, DataPackageTestClient.DataPackageClientService.TargetAddressType pElementAddress, string pBLVersion, System.DateTime pActDate, System.DateTime pExpDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:DataPackage/IDataPackageService/assignCurrentBaselineToElement", ReplyAction="urn:DataPackage/IDataPackageService/assignCurrentBaselineToElementResponse")]
        DataPackageTestClient.DataPackageClientService.DataTypeErrorPlusReqId assignCurrentBaselineToElement(System.Guid pSessionId, DataPackageTestClient.DataPackageClientService.TargetAddressType pElementAddress, string pBLVersion, System.DateTime pExpDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:DataPackage/IDataPackageService/distibuteBaseline", ReplyAction="urn:DataPackage/IDataPackageService/distibuteBaselineResponse")]
        DataPackageTestClient.DataPackageClientService.DataTypeErrorPlusReqId distibuteBaseline(System.Guid pSessionId, DataPackageTestClient.DataPackageClientService.TargetAddressType pElementAddress, DataPackageTestClient.DataPackageClientService.BaselineDistributionAttributes pBLAttributes, uint pReqTimeout);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:DataPackage/IDataPackageService/forceAddresseesFutureBaseline", ReplyAction="urn:DataPackage/IDataPackageService/forceAddresseesFutureBaselineResponse")]
        DataPackageTestClient.DataPackageClientService.DataTypeErrorPlusReqId forceAddresseesFutureBaseline(System.Guid pSessionId, DataPackageTestClient.DataPackageClientService.TargetAddressType pElementAddress, uint pReqTimeout);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:DataPackage/IDataPackageService/forceAddresseesArchivedBaseline", ReplyAction="urn:DataPackage/IDataPackageService/forceAddresseesArchivedBaselineResponse")]
        DataPackageTestClient.DataPackageClientService.DataTypeErrorPlusReqId forceAddresseesArchivedBaseline(System.Guid pSessionId, DataPackageTestClient.DataPackageClientService.TargetAddressType pElementAddress, uint pReqTimeout);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:DataPackage/IDataPackageService/clearAddreeseesFocingStatus", ReplyAction="urn:DataPackage/IDataPackageService/clearAddreeseesFocingStatusResponse")]
        DataPackageTestClient.DataPackageClientService.DataTypeErrorPlusReqId clearAddreeseesFocingStatus(System.Guid pSessionId, DataPackageTestClient.DataPackageClientService.TargetAddressType pElementAddress, uint pReqTimeout);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IDataPackageServiceChannel : DataPackageTestClient.DataPackageClientService.IDataPackageService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class DataPackageServiceClient : System.ServiceModel.ClientBase<DataPackageTestClient.DataPackageClientService.IDataPackageService>, DataPackageTestClient.DataPackageClientService.IDataPackageService {
        
        public DataPackageServiceClient() {
        }
        
        public DataPackageServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DataPackageServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataPackageServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataPackageServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public DataPackageTestClient.DataPackageClientService.DataTypeErrorPlusBaselineDefinitionList getBaselinesList(System.Guid pSessionId) {
            return base.Channel.getBaselinesList(pSessionId);
        }
        
        public DataPackageTestClient.DataPackageClientService.DataTypeErrorPlusElementDescriptionList getAddresseesDataPackagesBaselines(System.Guid pSessionId, DataPackageTestClient.DataPackageClientService.TargetAddressType pElementAddress) {
            return base.Channel.getAddresseesDataPackagesBaselines(pSessionId, pElementAddress);
        }
        
        public DataPackageTestClient.DataPackageClientService.DataTypeErrorPlusReqId uploadDataPackages(System.Guid pSessionId, string[] pFilesURLs) {
            return base.Channel.uploadDataPackages(pSessionId, pFilesURLs);
        }
        
        public DataPackageTestClient.DataPackageClientService.DataTypeErrorPlusReqId defineNewBaseline(System.Guid pSessionId, DataPackageTestClient.DataPackageClientService.BaselineDefinition pBLDef) {
            return base.Channel.defineNewBaseline(pSessionId, pBLDef);
        }
        
        public DataPackageTestClient.DataPackageClientService.DataTypeErrorPlusReqId assignFutureBaselineToElement(System.Guid pSessionId, DataPackageTestClient.DataPackageClientService.TargetAddressType pElementAddress, string pBLVersion, System.DateTime pActDate, System.DateTime pExpDate) {
            return base.Channel.assignFutureBaselineToElement(pSessionId, pElementAddress, pBLVersion, pActDate, pExpDate);
        }
        
        public DataPackageTestClient.DataPackageClientService.DataTypeErrorPlusReqId assignCurrentBaselineToElement(System.Guid pSessionId, DataPackageTestClient.DataPackageClientService.TargetAddressType pElementAddress, string pBLVersion, System.DateTime pExpDate) {
            return base.Channel.assignCurrentBaselineToElement(pSessionId, pElementAddress, pBLVersion, pExpDate);
        }
        
        public DataPackageTestClient.DataPackageClientService.DataTypeErrorPlusReqId distibuteBaseline(System.Guid pSessionId, DataPackageTestClient.DataPackageClientService.TargetAddressType pElementAddress, DataPackageTestClient.DataPackageClientService.BaselineDistributionAttributes pBLAttributes, uint pReqTimeout) {
            return base.Channel.distibuteBaseline(pSessionId, pElementAddress, pBLAttributes, pReqTimeout);
        }
        
        public DataPackageTestClient.DataPackageClientService.DataTypeErrorPlusReqId forceAddresseesFutureBaseline(System.Guid pSessionId, DataPackageTestClient.DataPackageClientService.TargetAddressType pElementAddress, uint pReqTimeout) {
            return base.Channel.forceAddresseesFutureBaseline(pSessionId, pElementAddress, pReqTimeout);
        }
        
        public DataPackageTestClient.DataPackageClientService.DataTypeErrorPlusReqId forceAddresseesArchivedBaseline(System.Guid pSessionId, DataPackageTestClient.DataPackageClientService.TargetAddressType pElementAddress, uint pReqTimeout) {
            return base.Channel.forceAddresseesArchivedBaseline(pSessionId, pElementAddress, pReqTimeout);
        }
        
        public DataPackageTestClient.DataPackageClientService.DataTypeErrorPlusReqId clearAddreeseesFocingStatus(System.Guid pSessionId, DataPackageTestClient.DataPackageClientService.TargetAddressType pElementAddress, uint pReqTimeout) {
            return base.Channel.clearAddreeseesFocingStatus(pSessionId, pElementAddress, pReqTimeout);
        }
    }
}
