//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :2.0.50727.5485
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIS.Ground.DataPackage.DataPackageSync
{
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultEnumType", Namespace="http://alstom.com/pacis/pis/schema/ground/datapackagesync/")]
    public enum ResultEnumType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Failure = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BaselineNotFound = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidElementId = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RemoteDataStoreNotAccessible = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PackageNotFound = 5,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://alstom.com/pacis/pis/ground/datapackagesync/", ConfigurationName="PIS.Ground.DataPackage.DataPackageSync.IDataPackageSyncGroundService")]
    public interface IDataPackageSyncGroundService
    {
        
        // CODEGEN : La génération du contrat de message depuis l’espace de noms de wrapper (http://alstom.com/pacis/pis/schema/ground/datapackagesync/) du message GetAssignedBaselineVersionRequest ne correspond pas à la valeur par défaut (http://alstom.com/pacis/pis/ground/datapackagesync/)
        [System.ServiceModel.OperationContractAttribute(Action="http://alstom.com/pacis/pis/ground/dataPackageSync/GetAssignedBaselineVersion", ReplyAction="*")]
        PIS.Ground.DataPackage.DataPackageSync.GetAssignedBaselineVersionResponse GetAssignedBaselineVersion(PIS.Ground.DataPackage.DataPackageSync.GetAssignedBaselineVersionRequest request);
        
        // CODEGEN : La génération du contrat de message depuis l’espace de noms de wrapper (http://alstom.com/pacis/pis/schema/ground/datapackagesync/) du message RequestBaselineRequest ne correspond pas à la valeur par défaut (http://alstom.com/pacis/pis/ground/datapackagesync/)
        [System.ServiceModel.OperationContractAttribute(Action="http://alstom.com/pacis/pis/ground/dataPackageSync/RequestBaseline", ReplyAction="*")]
        PIS.Ground.DataPackage.DataPackageSync.RequestBaselineResponse RequestBaseline(PIS.Ground.DataPackage.DataPackageSync.RequestBaselineRequest request);
        
        // CODEGEN : La génération du contrat de message depuis l’espace de noms de wrapper (http://alstom.com/pacis/pis/schema/ground/datapackagesync/) du message RequestAssignedBaselineRequest ne correspond pas à la valeur par défaut (http://alstom.com/pacis/pis/ground/datapackagesync/)
        [System.ServiceModel.OperationContractAttribute(Action="http://alstom.com/pacis/pis/ground/dataPackageSync/RequestAssignedBaseline", ReplyAction="*")]
        PIS.Ground.DataPackage.DataPackageSync.RequestAssignedBaselineResponse RequestAssignedBaseline(PIS.Ground.DataPackage.DataPackageSync.RequestAssignedBaselineRequest request);
        
        // CODEGEN : La génération du contrat de message depuis l’espace de noms de wrapper (http://alstom.com/pacis/pis/schema/ground/datapackagesync/) du message RequestBaselineVersionRequest ne correspond pas à la valeur par défaut (http://alstom.com/pacis/pis/ground/datapackagesync/)
        [System.ServiceModel.OperationContractAttribute(Action="http://alstom.com/pacis/pis/ground/dataPackageSync/RequestBaselineVersion", ReplyAction="*")]
        PIS.Ground.DataPackage.DataPackageSync.RequestBaselineVersionResponse RequestBaselineVersion(PIS.Ground.DataPackage.DataPackageSync.RequestBaselineVersionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAssignedBaselineVersionRequest", WrapperNamespace="http://alstom.com/pacis/pis/schema/ground/datapackagesync/", IsWrapped=true)]
    public partial class GetAssignedBaselineVersionRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://alstom.com/pacis/pis/schema/ground/datapackagesync/", Order=0)]
        public string ElementId;
        
        public GetAssignedBaselineVersionRequest()
        {
        }
        
        public GetAssignedBaselineVersionRequest(string ElementId)
        {
            this.ElementId = ElementId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAssignedBaselineVersionResponse", WrapperNamespace="http://alstom.com/pacis/pis/schema/ground/datapackagesync/", IsWrapped=true)]
    public partial class GetAssignedBaselineVersionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://alstom.com/pacis/pis/schema/ground/datapackagesync/", Order=0)]
        public PIS.Ground.DataPackage.DataPackageSync.ResultEnumType Result;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://alstom.com/pacis/pis/schema/ground/datapackagesync/", Order=1)]
        public string CurrentVersion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://alstom.com/pacis/pis/schema/ground/datapackagesync/", Order=2)]
        public string FutureVersion;
        
        public GetAssignedBaselineVersionResponse()
        {
        }
        
        public GetAssignedBaselineVersionResponse(PIS.Ground.DataPackage.DataPackageSync.ResultEnumType Result, string CurrentVersion, string FutureVersion)
        {
            this.Result = Result;
            this.CurrentVersion = CurrentVersion;
            this.FutureVersion = FutureVersion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RequestBaselineRequest", WrapperNamespace="http://alstom.com/pacis/pis/schema/ground/datapackagesync/", IsWrapped=true)]
    public partial class RequestBaselineRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://alstom.com/pacis/pis/schema/ground/datapackagesync/", Order=0)]
        public string ElementId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://alstom.com/pacis/pis/schema/ground/datapackagesync/", Order=1)]
        public string Version;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://alstom.com/pacis/pis/schema/ground/datapackagesync/", Order=2)]
        public System.DateTime ActivationDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://alstom.com/pacis/pis/schema/ground/datapackagesync/", Order=3)]
        public System.DateTime ExpirationDate;
        
        public RequestBaselineRequest()
        {
        }
        
        public RequestBaselineRequest(string ElementId, string Version, System.DateTime ActivationDate, System.DateTime ExpirationDate)
        {
            this.ElementId = ElementId;
            this.Version = Version;
            this.ActivationDate = ActivationDate;
            this.ExpirationDate = ExpirationDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RequestBaselineResponse", WrapperNamespace="http://alstom.com/pacis/pis/schema/ground/datapackagesync/", IsWrapped=true)]
    public partial class RequestBaselineResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://alstom.com/pacis/pis/schema/ground/datapackagesync/", Order=0)]
        public PIS.Ground.DataPackage.DataPackageSync.ResultEnumType Result;
        
        public RequestBaselineResponse()
        {
        }
        
        public RequestBaselineResponse(PIS.Ground.DataPackage.DataPackageSync.ResultEnumType Result)
        {
            this.Result = Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RequestAssignedBaselineRequest", WrapperNamespace="http://alstom.com/pacis/pis/schema/ground/datapackagesync/", IsWrapped=true)]
    public partial class RequestAssignedBaselineRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://alstom.com/pacis/pis/schema/ground/datapackagesync/", Order=0)]
        public string ElementId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://alstom.com/pacis/pis/schema/ground/datapackagesync/", Order=1)]
        public bool Current;
        
        public RequestAssignedBaselineRequest()
        {
        }
        
        public RequestAssignedBaselineRequest(string ElementId, bool Current)
        {
            this.ElementId = ElementId;
            this.Current = Current;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RequestAssignedBaselineResponse", WrapperNamespace="http://alstom.com/pacis/pis/schema/ground/datapackagesync/", IsWrapped=true)]
    public partial class RequestAssignedBaselineResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://alstom.com/pacis/pis/schema/ground/datapackagesync/", Order=0)]
        public PIS.Ground.DataPackage.DataPackageSync.ResultEnumType Result;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://alstom.com/pacis/pis/schema/ground/datapackagesync/", Order=1)]
        public string Version;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://alstom.com/pacis/pis/schema/ground/datapackagesync/", Order=2)]
        public System.DateTime ActivationDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://alstom.com/pacis/pis/schema/ground/datapackagesync/", Order=3)]
        public System.DateTime ExpirationDate;
        
        public RequestAssignedBaselineResponse()
        {
        }
        
        public RequestAssignedBaselineResponse(PIS.Ground.DataPackage.DataPackageSync.ResultEnumType Result, string Version, System.DateTime ActivationDate, System.DateTime ExpirationDate)
        {
            this.Result = Result;
            this.Version = Version;
            this.ActivationDate = ActivationDate;
            this.ExpirationDate = ExpirationDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RequestBaselineVersionRequest", WrapperNamespace="http://alstom.com/pacis/pis/schema/ground/datapackagesync/", IsWrapped=true)]
    public partial class RequestBaselineVersionRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://alstom.com/pacis/pis/schema/ground/datapackagesync/", Order=0)]
        public string ElementId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://alstom.com/pacis/pis/schema/ground/datapackagesync/", Order=1)]
        public string PisBaseVersion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://alstom.com/pacis/pis/schema/ground/datapackagesync/", Order=2)]
        public string PisMissionVersion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://alstom.com/pacis/pis/schema/ground/datapackagesync/", Order=3)]
        public string PisInfotainmentVersion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://alstom.com/pacis/pis/schema/ground/datapackagesync/", Order=4)]
        public string LmtVersion;
        
        public RequestBaselineVersionRequest()
        {
        }
        
        public RequestBaselineVersionRequest(string ElementId, string PisBaseVersion, string PisMissionVersion, string PisInfotainmentVersion, string LmtVersion)
        {
            this.ElementId = ElementId;
            this.PisBaseVersion = PisBaseVersion;
            this.PisMissionVersion = PisMissionVersion;
            this.PisInfotainmentVersion = PisInfotainmentVersion;
            this.LmtVersion = LmtVersion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RequestBaselineVersionResponse", WrapperNamespace="http://alstom.com/pacis/pis/schema/ground/datapackagesync/", IsWrapped=true)]
    public partial class RequestBaselineVersionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://alstom.com/pacis/pis/schema/ground/datapackagesync/", Order=0)]
        public PIS.Ground.DataPackage.DataPackageSync.ResultEnumType Result;
        
        public RequestBaselineVersionResponse()
        {
        }
        
        public RequestBaselineVersionResponse(PIS.Ground.DataPackage.DataPackageSync.ResultEnumType Result)
        {
            this.Result = Result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IDataPackageSyncGroundServiceChannel : PIS.Ground.DataPackage.DataPackageSync.IDataPackageSyncGroundService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class DataPackageSyncGroundServiceClient : System.ServiceModel.ClientBase<PIS.Ground.DataPackage.DataPackageSync.IDataPackageSyncGroundService>, PIS.Ground.DataPackage.DataPackageSync.IDataPackageSyncGroundService
    {
        
        public DataPackageSyncGroundServiceClient()
        {
        }
        
        public DataPackageSyncGroundServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public DataPackageSyncGroundServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public DataPackageSyncGroundServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public DataPackageSyncGroundServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PIS.Ground.DataPackage.DataPackageSync.GetAssignedBaselineVersionResponse PIS.Ground.DataPackage.DataPackageSync.IDataPackageSyncGroundService.GetAssignedBaselineVersion(PIS.Ground.DataPackage.DataPackageSync.GetAssignedBaselineVersionRequest request)
        {
            return base.Channel.GetAssignedBaselineVersion(request);
        }
        
        public PIS.Ground.DataPackage.DataPackageSync.ResultEnumType GetAssignedBaselineVersion(string ElementId, out string CurrentVersion, out string FutureVersion)
        {
            PIS.Ground.DataPackage.DataPackageSync.GetAssignedBaselineVersionRequest inValue = new PIS.Ground.DataPackage.DataPackageSync.GetAssignedBaselineVersionRequest();
            inValue.ElementId = ElementId;
            PIS.Ground.DataPackage.DataPackageSync.GetAssignedBaselineVersionResponse retVal = ((PIS.Ground.DataPackage.DataPackageSync.IDataPackageSyncGroundService)(this)).GetAssignedBaselineVersion(inValue);
            CurrentVersion = retVal.CurrentVersion;
            FutureVersion = retVal.FutureVersion;
            return retVal.Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PIS.Ground.DataPackage.DataPackageSync.RequestBaselineResponse PIS.Ground.DataPackage.DataPackageSync.IDataPackageSyncGroundService.RequestBaseline(PIS.Ground.DataPackage.DataPackageSync.RequestBaselineRequest request)
        {
            return base.Channel.RequestBaseline(request);
        }
        
        public PIS.Ground.DataPackage.DataPackageSync.ResultEnumType RequestBaseline(string ElementId, string Version, System.DateTime ActivationDate, System.DateTime ExpirationDate)
        {
            PIS.Ground.DataPackage.DataPackageSync.RequestBaselineRequest inValue = new PIS.Ground.DataPackage.DataPackageSync.RequestBaselineRequest();
            inValue.ElementId = ElementId;
            inValue.Version = Version;
            inValue.ActivationDate = ActivationDate;
            inValue.ExpirationDate = ExpirationDate;
            PIS.Ground.DataPackage.DataPackageSync.RequestBaselineResponse retVal = ((PIS.Ground.DataPackage.DataPackageSync.IDataPackageSyncGroundService)(this)).RequestBaseline(inValue);
            return retVal.Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PIS.Ground.DataPackage.DataPackageSync.RequestAssignedBaselineResponse PIS.Ground.DataPackage.DataPackageSync.IDataPackageSyncGroundService.RequestAssignedBaseline(PIS.Ground.DataPackage.DataPackageSync.RequestAssignedBaselineRequest request)
        {
            return base.Channel.RequestAssignedBaseline(request);
        }
        
        public PIS.Ground.DataPackage.DataPackageSync.ResultEnumType RequestAssignedBaseline(string ElementId, bool Current, out string Version, out System.DateTime ActivationDate, out System.DateTime ExpirationDate)
        {
            PIS.Ground.DataPackage.DataPackageSync.RequestAssignedBaselineRequest inValue = new PIS.Ground.DataPackage.DataPackageSync.RequestAssignedBaselineRequest();
            inValue.ElementId = ElementId;
            inValue.Current = Current;
            PIS.Ground.DataPackage.DataPackageSync.RequestAssignedBaselineResponse retVal = ((PIS.Ground.DataPackage.DataPackageSync.IDataPackageSyncGroundService)(this)).RequestAssignedBaseline(inValue);
            Version = retVal.Version;
            ActivationDate = retVal.ActivationDate;
            ExpirationDate = retVal.ExpirationDate;
            return retVal.Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PIS.Ground.DataPackage.DataPackageSync.RequestBaselineVersionResponse PIS.Ground.DataPackage.DataPackageSync.IDataPackageSyncGroundService.RequestBaselineVersion(PIS.Ground.DataPackage.DataPackageSync.RequestBaselineVersionRequest request)
        {
            return base.Channel.RequestBaselineVersion(request);
        }
        
        public PIS.Ground.DataPackage.DataPackageSync.ResultEnumType RequestBaselineVersion(string ElementId, string PisBaseVersion, string PisMissionVersion, string PisInfotainmentVersion, string LmtVersion)
        {
            PIS.Ground.DataPackage.DataPackageSync.RequestBaselineVersionRequest inValue = new PIS.Ground.DataPackage.DataPackageSync.RequestBaselineVersionRequest();
            inValue.ElementId = ElementId;
            inValue.PisBaseVersion = PisBaseVersion;
            inValue.PisMissionVersion = PisMissionVersion;
            inValue.PisInfotainmentVersion = PisInfotainmentVersion;
            inValue.LmtVersion = LmtVersion;
            PIS.Ground.DataPackage.DataPackageSync.RequestBaselineVersionResponse retVal = ((PIS.Ground.DataPackage.DataPackageSync.IDataPackageSyncGroundService)(this)).RequestBaselineVersion(inValue);
            return retVal.Result;
        }
    }
}
