//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5485
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIS.Ground.DataPackage {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Logs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Logs() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DataPackage.Logs", typeof(Logs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign baseline {0} as current to element {1}..
        /// </summary>
        internal static string DEBUG_ASSIGN_CURRENT_BASELINE {
            get {
                return ResourceManager.GetString("DEBUG_ASSIGN_CURRENT_BASELINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign baseline {0} as future to element {1}..
        /// </summary>
        internal static string DEBUG_ASSIGN_FUTURE_BASELINE {
            get {
                return ResourceManager.GetString("DEBUG_ASSIGN_FUTURE_BASELINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entering function {0}..
        /// </summary>
        internal static string DEBUG_ENTERING_FUNCTION {
            get {
                return ResourceManager.GetString("DEBUG_ENTERING_FUNCTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to assign {0} baseline {1} for element {2}..
        /// </summary>
        internal static string ERROR_ASSIGN_BASELINE_FAILED {
            get {
                return ResourceManager.GetString("ERROR_ASSIGN_BASELINE_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baseline {0} is assigned to an element.
        /// </summary>
        internal static string ERROR_BASELINE_IS_ASSIGNED {
            get {
                return ResourceManager.GetString("ERROR_BASELINE_IS_ASSIGNED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no baselines with version provided.
        /// </summary>
        internal static string ERROR_BASELINE_NOT_FOUND {
            get {
                return ResourceManager.GetString("ERROR_BASELINE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create a baseline distribution request to element &apos;{0}&apos; for baseline &apos;{1}&apos;..
        /// </summary>
        internal static string ERROR_CREATE_DISTRIBUTION_REQUEST {
            get {
                return ResourceManager.GetString("ERROR_CREATE_DISTRIBUTION_REQUEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data package is assigned and deleting isn&apos;t forced: type - {0}; version - {1}.
        /// </summary>
        internal static string ERROR_DATAPACKAGE_IS_ASSIGNED {
            get {
                return ResourceManager.GetString("ERROR_DATAPACKAGE_IS_ASSIGNED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data package is used : type - {0}; version - {1}.
        /// </summary>
        internal static string ERROR_DATAPACKAGE_IS_USED {
            get {
                return ResourceManager.GetString("ERROR_DATAPACKAGE_IS_USED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data package wasn&apos;t found : type - {0}; version - {1}.
        /// </summary>
        internal static string ERROR_DATAPACKAGE_ISNT_FOUND {
            get {
                return ResourceManager.GetString("ERROR_DATAPACKAGE_ISNT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while distributing baseline &apos;{0}&apos; to element &apos;{1}&apos;: &apos;{2}&apos;..
        /// </summary>
        internal static string ERROR_DISTRIBUTE_BASELINE_FAILED {
            get {
                return ResourceManager.GetString("ERROR_DISTRIBUTE_BASELINE_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while distributing baseline to element &apos;{0}&apos;: baseline version is unknown..
        /// </summary>
        internal static string ERROR_DISTRIBUTE_BASELINE_FAILED_UNKNOW_BASELINE_VERSION {
            get {
                return ResourceManager.GetString("ERROR_DISTRIBUTE_BASELINE_FAILED_UNKNOW_BASELINE_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot get information for element with ID: {0}..
        /// </summary>
        internal static string ERROR_ELEMENT_INFO {
            get {
                return ResourceManager.GetString("ERROR_ELEMENT_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The element is offline..
        /// </summary>
        internal static string ERROR_ELEMENT_IS_OFFLINE {
            get {
                return ResourceManager.GetString("ERROR_ELEMENT_IS_OFFLINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element {0} not found in local data store..
        /// </summary>
        internal static string ERROR_ELEMENT_NOT_FOUND {
            get {
                return ResourceManager.GetString("ERROR_ELEMENT_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting URLs list error.
        /// </summary>
        internal static string ERROR_GETTING_URL_LIST {
            get {
                return ResourceManager.GetString("ERROR_GETTING_URL_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input activation date is newer than expiration date ({0} &lt; {1})..
        /// </summary>
        internal static string ERROR_INVALID_ACTIVATION_DATE {
            get {
                return ResourceManager.GetString("ERROR_INVALID_ACTIVATION_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t process distributing baseline with an invalid request context..
        /// </summary>
        internal static string ERROR_INVALID_BASELINE_DISTRIBUTE_REQUEST_CONTEXT {
            get {
                return ResourceManager.GetString("ERROR_INVALID_BASELINE_DISTRIBUTE_REQUEST_CONTEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provided baseline version is not valid : {0}..
        /// </summary>
        internal static string ERROR_INVALID_BASELINE_VERSION {
            get {
                return ResourceManager.GetString("ERROR_INVALID_BASELINE_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provided data package version is not valid : {0}..
        /// </summary>
        internal static string ERROR_INVALID_DATAPACKAGE_VERSION {
            get {
                return ResourceManager.GetString("ERROR_INVALID_DATAPACKAGE_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input expiration date is older than current date ({0} &lt; {1})..
        /// </summary>
        internal static string ERROR_INVALID_EXPIRATION_DATE {
            get {
                return ResourceManager.GetString("ERROR_INVALID_EXPIRATION_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to generate a valid request id..
        /// </summary>
        internal static string ERROR_INVALID_REQUEST_ID {
            get {
                return ResourceManager.GetString("ERROR_INVALID_REQUEST_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SessionId {0} is not valid..
        /// </summary>
        internal static string ERROR_INVALID_SESSION_ID {
            get {
                return ResourceManager.GetString("ERROR_INVALID_SESSION_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RemoteDataStore is in faulted state..
        /// </summary>
        internal static string ERROR_REMOTEDATASTORE_FAULTED {
            get {
                return ResourceManager.GetString("ERROR_REMOTEDATASTORE_FAULTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to send request to RemoteDataStore, check if it&apos;s running and accessible!.
        /// </summary>
        internal static string ERROR_REMOTEDATASTORE_NOT_ACCESSIBLE {
            get {
                return ResourceManager.GetString("ERROR_REMOTEDATASTORE_NOT_ACCESSIBLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing request ... context is null.
        /// </summary>
        internal static string ERROR_REQUEST_PROCESSING {
            get {
                return ResourceManager.GetString("ERROR_REQUEST_PROCESSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The service info wasn&apos;t found..
        /// </summary>
        internal static string ERROR_SERVICE_INFO_NOT_FOUND {
            get {
                return ResourceManager.GetString("ERROR_SERVICE_INFO_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some baselines are assigned to the elements..
        /// </summary>
        internal static string ERROR_SOME_BASELINE_ARE_ASSIGNED {
            get {
                return ResourceManager.GetString("ERROR_SOME_BASELINE_ARE_ASSIGNED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T2G Ground server is not responding..
        /// </summary>
        internal static string ERROR_T2G_SERVER_OFFLINE {
            get {
                return ResourceManager.GetString("ERROR_T2G_SERVER_OFFLINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure to cancel transfer tasks: {0}..
        /// </summary>
        internal static string ERROR_TRANSFER_TASKS_CANCELING {
            get {
                return ResourceManager.GetString("ERROR_TRANSFER_TASKS_CANCELING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot send notification to ground applications: the notification sender object is undefined.
        /// </summary>
        internal static string ERROR_UNDEFINED_NOTIFICATION_SENDER {
            get {
                return ResourceManager.GetString("ERROR_UNDEFINED_NOTIFICATION_SENDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown baseline version for element {0}.
        /// </summary>
        internal static string ERROR_UNKNOWN_BASELINE_VERSION {
            get {
                return ResourceManager.GetString("ERROR_UNKNOWN_BASELINE_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distributing baseline on element {0}..
        /// </summary>
        internal static string INFO_BASELINE_DISTRIBUTING {
            get {
                return ResourceManager.GetString("INFO_BASELINE_DISTRIBUTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}  called.
        /// </summary>
        internal static string INFO_FUNCTION_CALLED {
            get {
                return ResourceManager.GetString("INFO_FUNCTION_CALLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} exception.
        /// </summary>
        internal static string INFO_FUNCTION_EXCEPTION {
            get {
                return ResourceManager.GetString("INFO_FUNCTION_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} exception : {1}.
        /// </summary>
        internal static string INFO_FUNCTION_EXCEPTION_MESSAGE {
            get {
                return ResourceManager.GetString("INFO_FUNCTION_EXCEPTION_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Future baseline for element {0}  is {1}..
        /// </summary>
        internal static string INFO_FUTURE_BASELINE {
            get {
                return ResourceManager.GetString("INFO_FUTURE_BASELINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of transfer tasks from T2G = {0}..
        /// </summary>
        internal static string INFO_LIST_OF_TRANSFER_TASKS {
            get {
                return ResourceManager.GetString("INFO_LIST_OF_TRANSFER_TASKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Woke up. New events to process....
        /// </summary>
        internal static string INFO_NEW_EVENTS_TO_PROCESS {
            get {
                return ResourceManager.GetString("INFO_NEW_EVENTS_TO_PROCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No events to process. Sleeping....
        /// </summary>
        internal static string INFO_NO_EVENTS_TO_PROCESS {
            get {
                return ResourceManager.GetString("INFO_NO_EVENTS_TO_PROCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sendNotificationToGroundApp : ReqID = {0}; pStatus = {1}..
        /// </summary>
        internal static string INFO_NOTIFICATIONTOAPPGROUND {
            get {
                return ResourceManager.GetString("INFO_NOTIFICATIONTOAPPGROUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of pending cancellable transfers : {0}..
        /// </summary>
        internal static string INFO_PENDING_TRANSFERS_LIST {
            get {
                return ResourceManager.GetString("INFO_PENDING_TRANSFERS_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request is expired..
        /// </summary>
        internal static string INFO_REQUEST_IS_EXPIRED {
            get {
                return ResourceManager.GetString("INFO_REQUEST_IS_EXPIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing request....
        /// </summary>
        internal static string INFO_REQUEST_PROCESSING {
            get {
                return ResourceManager.GetString("INFO_REQUEST_PROCESSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving information for tranfer task id {0} from T2G..
        /// </summary>
        internal static string INFO_RETRIEVE_TRANSFER_TASK_ID {
            get {
                return ResourceManager.GetString("INFO_RETRIEVE_TRANSFER_TASK_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success cancelling previous task(s): {0}..
        /// </summary>
        internal static string INFO_TASK_IS_CANCELED {
            get {
                return ResourceManager.GetString("INFO_TASK_IS_CANCELED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found task id {0} from local distribution list. Recipient(s) info: {1}..
        /// </summary>
        internal static string INFO_TRANSFER_TASK_PARAMS {
            get {
                return ResourceManager.GetString("INFO_TRANSFER_TASK_PARAMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information for tranfer task id {0} from T2G. Recipient(s) info: {1}..
        /// </summary>
        internal static string INFO_TRANSFER_TASK_PARAMS_FROM_T2G {
            get {
                return ResourceManager.GetString("INFO_TRANSFER_TASK_PARAMS_FROM_T2G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure to retrieve information for tranfer task id {0} from T2G..
        /// </summary>
        internal static string WARNING_CANT_RETRIVE_TRANSFER_TASK_INFO {
            get {
                return ResourceManager.GetString("WARNING_CANT_RETRIVE_TRANSFER_TASK_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Got an incomplete tranfer task list from T2G..
        /// </summary>
        internal static string WARNING_INCOMPLETE_TRANSFER_TASKS_LIST {
            get {
                return ResourceManager.GetString("WARNING_INCOMPLETE_TRANSFER_TASKS_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find baseline version associated to request &apos;{0}&apos; for element &apos;{1}&apos;..
        /// </summary>
        internal static string WARNING_NO_BASELINE_VERSION_FOUND {
            get {
                return ResourceManager.GetString("WARNING_NO_BASELINE_VERSION_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem getting the list of pending transfers..
        /// </summary>
        internal static string WARNING_PENDING_TRANSFERS_LIST {
            get {
                return ResourceManager.GetString("WARNING_PENDING_TRANSFERS_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem cancelling previous task(s): {0}..
        /// </summary>
        internal static string WARNING_TASK_CANCELING_PROBLEM {
            get {
                return ResourceManager.GetString("WARNING_TASK_CANCELING_PROBLEM", resourceCulture);
            }
        }
    }
}
