//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :2.0.50727.5485
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIS.Train.Mission
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="StationList", Namespace="http://alstom.com/pacis/pis/schema/train/mission/", ItemName="StationId")]
    public class StationList : System.Collections.Generic.List<string>
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultType", Namespace="http://alstom.com/pacis/pis/schema/train/mission/")]
    public enum ResultType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ErrorInvalidElementId = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ErrorMissionCodeDifferent = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ErrorUnknownLmtDb = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ErrorNoActiveMission = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ErrorServiceInhibited = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ErrorActiveMission = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Failure = 7,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://alstom.com/pacis/pis/train/mission/", ConfigurationName="PIS.Train.Mission.IMissionControlService")]
    public interface IMissionControlService
    {
        
        // CODEGEN : La génération du contrat de message depuis l’espace de noms de wrapper (http://alstom.com/pacis/pis/schema/train/mission/) du message InitializeMissionRequest ne correspond pas à la valeur par défaut (http://alstom.com/pacis/pis/train/mission/)
        [System.ServiceModel.OperationContractAttribute(Action="http://alstom.com/pacis/pis/train/Mission/InitializeMission", ReplyAction="*")]
        PIS.Train.Mission.InitializeMissionResponse InitializeMission(PIS.Train.Mission.InitializeMissionRequest request);
        
        // CODEGEN : La génération du contrat de message depuis l’espace de noms de wrapper (http://alstom.com/pacis/pis/schema/train/mission/) du message CancelMissionRequest ne correspond pas à la valeur par défaut (http://alstom.com/pacis/pis/train/mission/)
        [System.ServiceModel.OperationContractAttribute(Action="http://alstom.com/pacis/pis/train/Mission/CancelMission", ReplyAction="*")]
        PIS.Train.Mission.CancelMissionResponse CancelMission(PIS.Train.Mission.CancelMissionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InitializeMission", WrapperNamespace="http://alstom.com/pacis/pis/schema/train/mission/", IsWrapped=true)]
    public partial class InitializeMissionRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://alstom.com/pacis/pis/schema/train/mission/", Order=0)]
        public string RequestId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://alstom.com/pacis/pis/schema/train/mission/", Order=1)]
        public string ElementId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://alstom.com/pacis/pis/schema/train/mission/", Order=2)]
        public string MissionCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://alstom.com/pacis/pis/schema/train/mission/", Order=3)]
        public string LmtDbVersion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://alstom.com/pacis/pis/schema/train/mission/", Order=4)]
        public PIS.Train.Mission.StationList StationList;
        
        public InitializeMissionRequest()
        {
        }
        
        public InitializeMissionRequest(string RequestId, string ElementId, string MissionCode, string LmtDbVersion, PIS.Train.Mission.StationList StationList)
        {
            this.RequestId = RequestId;
            this.ElementId = ElementId;
            this.MissionCode = MissionCode;
            this.LmtDbVersion = LmtDbVersion;
            this.StationList = StationList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InitializeMissionResponse", WrapperNamespace="http://alstom.com/pacis/pis/schema/train/mission/", IsWrapped=true)]
    public partial class InitializeMissionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://alstom.com/pacis/pis/schema/train/mission/", Order=0)]
        public PIS.Train.Mission.ResultType Result;
        
        public InitializeMissionResponse()
        {
        }
        
        public InitializeMissionResponse(PIS.Train.Mission.ResultType Result)
        {
            this.Result = Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CancelMission", WrapperNamespace="http://alstom.com/pacis/pis/schema/train/mission/", IsWrapped=true)]
    public partial class CancelMissionRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://alstom.com/pacis/pis/schema/train/mission/", Order=0)]
        public string RequestId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://alstom.com/pacis/pis/schema/train/mission/", Order=1)]
        public string ElementId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://alstom.com/pacis/pis/schema/train/mission/", Order=2)]
        public string MissionCode;
        
        public CancelMissionRequest()
        {
        }
        
        public CancelMissionRequest(string RequestId, string ElementId, string MissionCode)
        {
            this.RequestId = RequestId;
            this.ElementId = ElementId;
            this.MissionCode = MissionCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CancelMissionResponse", WrapperNamespace="http://alstom.com/pacis/pis/schema/train/mission/", IsWrapped=true)]
    public partial class CancelMissionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://alstom.com/pacis/pis/schema/train/mission/", Order=0)]
        public PIS.Train.Mission.ResultType Result;
        
        public CancelMissionResponse()
        {
        }
        
        public CancelMissionResponse(PIS.Train.Mission.ResultType Result)
        {
            this.Result = Result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IMissionControlServiceChannel : PIS.Train.Mission.IMissionControlService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class MissionControlServiceClient : System.ServiceModel.ClientBase<PIS.Train.Mission.IMissionControlService>, PIS.Train.Mission.IMissionControlService
    {
        
        public MissionControlServiceClient()
        {
        }
        
        public MissionControlServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public MissionControlServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public MissionControlServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public MissionControlServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PIS.Train.Mission.InitializeMissionResponse PIS.Train.Mission.IMissionControlService.InitializeMission(PIS.Train.Mission.InitializeMissionRequest request)
        {
            return base.Channel.InitializeMission(request);
        }
        
        public PIS.Train.Mission.ResultType InitializeMission(string RequestId, string ElementId, string MissionCode, string LmtDbVersion, PIS.Train.Mission.StationList StationList)
        {
            PIS.Train.Mission.InitializeMissionRequest inValue = new PIS.Train.Mission.InitializeMissionRequest();
            inValue.RequestId = RequestId;
            inValue.ElementId = ElementId;
            inValue.MissionCode = MissionCode;
            inValue.LmtDbVersion = LmtDbVersion;
            inValue.StationList = StationList;
            PIS.Train.Mission.InitializeMissionResponse retVal = ((PIS.Train.Mission.IMissionControlService)(this)).InitializeMission(inValue);
            return retVal.Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PIS.Train.Mission.CancelMissionResponse PIS.Train.Mission.IMissionControlService.CancelMission(PIS.Train.Mission.CancelMissionRequest request)
        {
            return base.Channel.CancelMission(request);
        }
        
        public PIS.Train.Mission.ResultType CancelMission(string RequestId, string ElementId, string MissionCode)
        {
            PIS.Train.Mission.CancelMissionRequest inValue = new PIS.Train.Mission.CancelMissionRequest();
            inValue.RequestId = RequestId;
            inValue.ElementId = ElementId;
            inValue.MissionCode = MissionCode;
            PIS.Train.Mission.CancelMissionResponse retVal = ((PIS.Train.Mission.IMissionControlService)(this)).CancelMission(inValue);
            return retVal.Result;
        }
    }
}
