//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :2.0.50727.8745
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIS.Ground.Mission.Notification
{
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NotificationIdEnum", Namespace="http://alstom.com/pacis/pis/schema/notification/")]
    public enum NotificationIdEnum : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DataPackageUploadProcessing = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DataPackageUploadCompleted = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DataPackageUploadAlreadyExist = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DataPackageUploadFailed = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DataPackageBaselineDefinitionProcessing = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DataPackageBaselineDefinitionCompleted = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DataPackageBaselineDefinitionFailed = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DataPackageBaselineAssignmentProcessing = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DataPackageBaselineAssignmentCompleted = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DataPackageBaselineAssignmentFailed = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DataPackageBaselineNotInstalled = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DataPackageBaselineUpdatePending = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DataPackageDistributionProcessing = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DataPackageDistributionWaitingToTransfer = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DataPackageDistributionTransferring = 14,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DataPackageDistributionTransferred = 15,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DataPackageDistributionCompleted = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DataPackageDistributionTimedOut = 17,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DataPackageDistributionFailedMissingDataPackage = 18,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DataPackageDistributionFailedNoAssignedFutureBaseline = 19,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DataPackageDistributionFailedTransferCancelledManually = 20,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DataPackageDistributionFailedRejectedByElement = 21,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DataPackageDistributionFailedUnknowOnBoardBaseline = 22,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DataPackageDistributionFailedUnknowOnBoardDataPackage = 23,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DataPackageDistributionInhibited = 24,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DataPackageDistributionUnknowElementId = 25,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DataPackageBaselineForcingProcessing = 26,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DataPackageBaselineForcingWaitingToSend = 27,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DataPackageBaselineForcingSent = 28,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DataPackageBaselineForcingCompleted = 29,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DataPackageBaselineForcingTimedOut = 30,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DataPackageBaselineForcingFailed = 31,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DataPackageBaselineForcingInhibited = 32,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DataPackageBaselineClearForcingProcessing = 33,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DataPackageBaselineClearForcingWaitingToSend = 34,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DataPackageBaselineClearForcingSent = 35,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DataPackageBaselineClearForcingCompleted = 36,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DataPackageBaselineClearForcingTimedOut = 37,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DataPackageBaselineClearForcingFailed = 38,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DataPackageBaselineClearForcingInhibited = 39,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DataPackageMissing = 40,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DataPackageFutureBaselineDefinition = 41,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DataPackageT2GServerOffline = 42,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DataPackageServiceStarted = 43,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InstantMessageUndefinedTemplateId = 44,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InstantMessageUndefinedStationId = 45,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InstantMessageUnknownCarId = 46,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InstantMessageInvalidDelay = 47,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InstantMessageInvalidDelayReasonCode = 48,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InstantMessageInvalidHour = 49,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InstantMessageInvalidScheduledPeriod = 50,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InstantMessageInvalidText = 51,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InstantMessageInvalidRepetitionCount = 52,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InstantMessageTemplateListUpdated = 53,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InstantMessageStationListUpdated = 54,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InstantMessageDistributionProcessing = 55,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InstantMessageDistributionWaitingToSend = 56,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InstantMessageDistributionSent = 57,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InstantMessageDistributionReceived = 58,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InstantMessageDistributionTimedOut = 59,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InstantMessageDistributionInhibited = 60,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InstantMessageMessageLimitExceeded = 61,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InstantMessageInternalError = 62,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InstantMessageElementNotFound = 63,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InstantMessageServiceNotFound = 64,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InstantMessageT2GServerOffline = 65,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InstantMessageTemplateFileNotValid = 66,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InstantMessageServiceStarted = 67,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MaintenanceDownloadProcessing = 68,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MaintenanceDownloadWaitingToSend = 69,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MaintenanceDownloadDownloading = 70,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MaintenanceDownloadCompleted = 71,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MaintenanceDownloadTimedOut = 72,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MaintenanceDownloadInhibited = 73,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MaintenanceDownloadElementNotFound = 74,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MaintenanceDownloadServiceNotFound = 75,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MaintenanceT2GServerOffline = 76,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MaintenanceServiceStarted = 77,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InfotainmentDownloadProcessing = 78,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InfotainmentDownloadWaitingToSend = 79,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InfotainmentDownloadDownloading = 80,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InfotainmentDownloadCompleted = 81,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InfotainmentDownloadTimedOut = 82,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InfotainmentDownloadInhibited = 83,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InfotainmentDownloadElementNotFound = 84,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InfotainmentDownloadServiceNotFound = 85,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InfotainmentT2GServerOffline = 86,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InfotainmentServiceStarted = 87,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MissionCommandProgressProcessing = 88,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MissionCommandProgressWaitingToSend = 89,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MissionCommandProgressSent = 90,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MissionCommandProgressSuccess = 91,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MissionCommandProgressTimedOut = 92,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MissionCommandProgressUnknownLmtDataPackageVersion = 93,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MissionCommandProgressPendingValidation = 94,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MissionCommandProgressUnknownElementId = 95,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MissionCommandProgressUnknownLanguageCode = 96,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MissionCommandProgressUnknownOnboardServiceCode = 97,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MissionCommandProgressUnknownMissionOperatorCode = 98,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MissionCommandProgressUnknownStationId = 99,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MissionCommandProgressUnknownServiceId = 100,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MissionCommandProgressInvalidServiceHours = 101,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MissionCommandProgressInvalidInsertionTypeCode = 102,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MissionCommandProgressInvalidCommercialNumberList = 103,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MissionCommandProgressUnknownInsertionStationId = 104,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MissionCommandProgressUnknownRegionCode = 105,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MissionCommandProgressInvalidCarNumberingOffsetCode = 106,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MissionCommandProgressInvalidStartDate = 107,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MissionCommandProgressInsertionStationIsNotInRoute = 108,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MissionCommandProgressLmtDataPackageVersionDifferent = 109,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MissionCommandProgressValidationRejected = 110,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MissionCommandProgressCancelledByNewCommand = 111,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MissionCommandProgressMissionIdDifferent = 112,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MissionCommandProgressNoActiveMission = 113,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MissionCommandProgressServiceInhibited = 114,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MissionCommandProgressTrainIsInMaintenanceMode = 115,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MissionCommandT2GServerOffline = 116,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MissionServiceStarted = 117,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CommonT2GServerOffline = 118,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CommonT2GServerOnline = 119,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Completed = 120,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Failed = 121,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ServiceInhibited = 122,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DataPackageBaselineDefinitionRequest = 123,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DataPackageAssignedPackageWasDeleted = 124,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LiveVideoControlVideoStreamingON = 125,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LiveVideoControlVideoStreamingOFF = 126,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LiveVideoControlErrorInvalidVideoStream = 127,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LiveVideoControlErrorVideoStreamingInterrupted = 128,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LiveVideoControlErrorNoStreamReceivedAfterStartCommand = 129,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LiveVideoControlErrorUndefined = 130,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LiveVideoControlDistributionProcessing = 131,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LiveVideoControlDistributionTimedOut = 132,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LiveVideoControlElementNotFound = 133,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LiveVideoControlDistributionWaitingToSend = 134,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LiveVideoControlServiceNotFound = 135,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LiveVideoControlDistributionSent = 136,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LiveVideoControlDistributionReceived = 137,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LiveVideoControlAutomaticMode = 138,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LiveVideoControlManualMode = 139,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LiveVideoControlT2GServerOffline = 140,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LiveVideoControlServiceStarted = 141,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DeletedElement = 142,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RealTimeServiceStarted = 143,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MissionCommandProgressActiveMissionOnElement = 144,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InfotainmentDownloadNoReportEntryFound = 145,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DataPackageDistributionPending = 146,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MissionCommandProgressOngoingBaselineActivation = 147,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DataPackageDistributionFailed = 148,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InstantMessageDistributionCanceled = 149,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://alstom.com/pacis/pis/ground/notification/", ConfigurationName="PIS.Ground.Mission.Notification.INotificationGroundService")]
    public interface INotificationGroundService
    {
        
        // CODEGEN : La génération du contrat de message depuis l’espace de noms de wrapper (http://alstom.com/pacis/pis/schema/ground/notification) du message SendNotificationRequest ne correspond pas à la valeur par défaut (http://alstom.com/pacis/pis/ground/notification/)
        [System.ServiceModel.OperationContractAttribute(Action="http://alstom.com/pacis/pis/ground/notification/SendNotification", ReplyAction="*")]
        PIS.Ground.Mission.Notification.SendNotificationResponse SendNotification(PIS.Ground.Mission.Notification.SendNotificationRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendNotificationRequest", WrapperNamespace="http://alstom.com/pacis/pis/schema/ground/notification", IsWrapped=true)]
    public partial class SendNotificationRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://alstom.com/pacis/pis/schema/ground/notification", Order=0)]
        public string RequestId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://alstom.com/pacis/pis/schema/ground/notification", Order=1)]
        public string ElementId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://alstom.com/pacis/pis/schema/ground/notification", Order=2)]
        public PIS.Ground.Mission.Notification.NotificationIdEnum NotificationId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://alstom.com/pacis/pis/schema/ground/notification", Order=3)]
        public string Parameter;
        
        public SendNotificationRequest()
        {
        }
        
        public SendNotificationRequest(string RequestId, string ElementId, PIS.Ground.Mission.Notification.NotificationIdEnum NotificationId, string Parameter)
        {
            this.RequestId = RequestId;
            this.ElementId = ElementId;
            this.NotificationId = NotificationId;
            this.Parameter = Parameter;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendNotificationResponse", WrapperNamespace="http://alstom.com/pacis/pis/schema/ground/notification", IsWrapped=true)]
    public partial class SendNotificationResponse
    {
        
        public SendNotificationResponse()
        {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface INotificationGroundServiceChannel : PIS.Ground.Mission.Notification.INotificationGroundService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class NotificationGroundServiceClient : System.ServiceModel.ClientBase<PIS.Ground.Mission.Notification.INotificationGroundService>, PIS.Ground.Mission.Notification.INotificationGroundService
    {
        
        public NotificationGroundServiceClient()
        {
        }
        
        public NotificationGroundServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public NotificationGroundServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public NotificationGroundServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public NotificationGroundServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PIS.Ground.Mission.Notification.SendNotificationResponse PIS.Ground.Mission.Notification.INotificationGroundService.SendNotification(PIS.Ground.Mission.Notification.SendNotificationRequest request)
        {
            return base.Channel.SendNotification(request);
        }
        
        public void SendNotification(string RequestId, string ElementId, PIS.Ground.Mission.Notification.NotificationIdEnum NotificationId, string Parameter)
        {
            PIS.Ground.Mission.Notification.SendNotificationRequest inValue = new PIS.Ground.Mission.Notification.SendNotificationRequest();
            inValue.RequestId = RequestId;
            inValue.ElementId = ElementId;
            inValue.NotificationId = NotificationId;
            inValue.Parameter = Parameter;
            PIS.Ground.Mission.Notification.SendNotificationResponse retVal = ((PIS.Ground.Mission.Notification.INotificationGroundService)(this)).SendNotification(inValue);
        }
    }
}
