//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8745
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIS.Ground.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PIS.Ground.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &apos;{0}&apos; for configuration parameter &apos;{1}&apos; is invalid and default value &apos;{2}&apos; is used. Acceptable values are &apos;{3}&apos; and &apos;{4}&apos;..
        /// </summary>
        internal static string ConfigurationErrorInvalidBooleanValue {
            get {
                return ResourceManager.GetString("ConfigurationErrorInvalidBooleanValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &apos;{0}&apos; for the configuration parameter &apos;{1}&apos; is an invalid integer value. Default value &apos;{2}&apos; is used..
        /// </summary>
        internal static string ConfigurationErrorInvalidIntegerParameterValueWithDefault {
            get {
                return ResourceManager.GetString("ConfigurationErrorInvalidIntegerParameterValueWithDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The required configuration parameter &apos;{0}&apos; is not specified. This default value will be used: &apos;{1}&apos;..
        /// </summary>
        internal static string ConfigurationErrorMissingParameter {
            get {
                return ResourceManager.GetString("ConfigurationErrorMissingParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataBase Structure Version is not valid.
        /// </summary>
        internal static string DataBaseStructureVersion {
            get {
                return ResourceManager.GetString("DataBaseStructureVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session ID does not Exist for the SessionID : {0}.
        /// </summary>
        internal static string ErrorSessionNotFound {
            get {
                return ResourceManager.GetString("ErrorSessionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Log Level set in configuration file is not valid.
        /// </summary>
        internal static string EventLogLevelValueInvalid {
            get {
                return ResourceManager.GetString("EventLogLevelValueInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UploadFile: exception when executing the registered callback _updateFileCompletionCallBack.
        /// </summary>
        internal static string ExceptionUpdateFileCallback {
            get {
                return ResourceManager.GetString("ExceptionUpdateFileCallback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Lite DataBase path could not be found in the configuration file..
        /// </summary>
        internal static string ExConnectionStringNotFound {
            get {
                return ResourceManager.GetString("ExConnectionStringNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to upload file {0}.
        /// </summary>
        internal static string ExFtpError {
            get {
                return ResourceManager.GetString("ExFtpError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Exception raised for uploading File {0}.
        /// </summary>
        internal static string ExFtpLogin {
            get {
                return ResourceManager.GetString("ExFtpLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument exception is raised for uploading File {0}.
        /// </summary>
        internal static string ExFtpLoginArgument {
            get {
                return ResourceManager.GetString("ExFtpLoginArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled exception raised for uploading File {0}.
        /// </summary>
        internal static string ExFtpLoginException {
            get {
                return ResourceManager.GetString("ExFtpLoginException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Occured while Inserting the LoginDetails of User : {0} to DataBase : Details:{1}.
        /// </summary>
        internal static string ExInsertLogin {
            get {
                return ResourceManager.GetString("ExInsertLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error UserName/Pwd empty while Inserting the LoginDetails to DataBase.
        /// </summary>
        internal static string ExInsertLoginValidation {
            get {
                return ResourceManager.GetString("ExInsertLoginValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Occured while Inserting the NavigationURL for the SessionID :{0} to the DataBase : Details:{1}.
        /// </summary>
        internal static string ExInsertNotificationURL {
            get {
                return ResourceManager.GetString("ExInsertNotificationURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error NotificationUrl empty while Adding the NotificationURL to DataBase.
        /// </summary>
        internal static string ExInsertNotificationUrlValidation {
            get {
                return ResourceManager.GetString("ExInsertNotificationUrlValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Error Occured. Details: {0}.
        /// </summary>
        internal static string ExInternalError {
            get {
                return ResourceManager.GetString("ExInternalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log file path string could not be found in the configuration file..
        /// </summary>
        internal static string ExLogFilePathNotFound {
            get {
                return ResourceManager.GetString("ExLogFilePathNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem in logging In to T2G Identification Service.
        /// </summary>
        internal static string ExLogT2GIdetificationService {
            get {
                return ResourceManager.GetString("ExLogT2GIdetificationService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Occured while Removing the Session for the SessionID :{0} from the DataBase :  Details:{1}.
        /// </summary>
        internal static string ExRemoveSession {
            get {
                return ResourceManager.GetString("ExRemoveSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Occured while Updating the Status of  RequestID :{0} to DataBase : Details :{1}.
        /// </summary>
        internal static string ExRequestID_StatusUpdate {
            get {
                return ResourceManager.GetString("ExRequestID_StatusUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Occured while Inserting the RequestID To Session for SessionID :{0} to DataBase : Details :{1}.
        /// </summary>
        internal static string ExRequestIDInsert {
            get {
                return ResourceManager.GetString("ExRequestIDInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request ID does not Exist {0}.
        /// </summary>
        internal static string ExRequestIDNotFound {
            get {
                return ResourceManager.GetString("ExRequestIDNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Occured while Selecting the NotificationUrl for the RequestID:{0} from the DataBase: Details:{1}.
        /// </summary>
        internal static string ExSelectNotificationUrl {
            get {
                return ResourceManager.GetString("ExSelectNotificationUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Occured while Selecting the NotificationUrl for the SessionID:{0} from the DataBase: Details:{1}.
        /// </summary>
        internal static string ExSelectNotificationUrlBySessionID {
            get {
                return ResourceManager.GetString("ExSelectNotificationUrlBySessionID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Occured while getting all the NotificationUrls from the DataBase: Details:{0}.
        /// </summary>
        internal static string ExSelectNotificationUrls {
            get {
                return ResourceManager.GetString("ExSelectNotificationUrls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Occured while Selecting the SessionDetails for the SessionID :{0} from the DataBase: Details:{1}.
        /// </summary>
        internal static string ExSelectSessionDetails {
            get {
                return ResourceManager.GetString("ExSelectSessionDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session DataBase not found.
        /// </summary>
        internal static string ExSessionDBNotFound {
            get {
                return ResourceManager.GetString("ExSessionDBNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session ID does not Exist while Removing the Session information for the SessionID : {0}.
        /// </summary>
        internal static string ExSessionNotFound {
            get {
                return ResourceManager.GetString("ExSessionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session Time Out could not be found in the configuration file..
        /// </summary>
        internal static string ExSessionTimeOutNotFound {
            get {
                return ResourceManager.GetString("ExSessionTimeOutNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session Time Out value not correct in the configuration file..
        /// </summary>
        internal static string ExSessionTimeOutNotValid {
            get {
                return ResourceManager.GetString("ExSessionTimeOutNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Occured while checking the unused Session from the DataBase : Details:{0}.
        /// </summary>
        internal static string ExSessionTimerCheckError {
            get {
                return ResourceManager.GetString("ExSessionTimerCheckError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session Timer Check could not be found in the configuration file..
        /// </summary>
        internal static string ExSessionTimerCheckNotFound {
            get {
                return ResourceManager.GetString("ExSessionTimerCheckNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session Timer Check Out value not correct in the configuration file..
        /// </summary>
        internal static string ExSessionTimerCheckNotValid {
            get {
                return ResourceManager.GetString("ExSessionTimerCheckNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Occured while Validating the Session for the SessionID :{0} from the DataBase : Details:{1}.
        /// </summary>
        internal static string ExValidateSessionDetails {
            get {
                return ResourceManager.GetString("ExValidateSessionDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder is not uploaded yet.
        /// </summary>
        internal static string FolderNotUploaded {
            get {
                return ResourceManager.GetString("FolderNotUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FTP upload is done, create transfer task..
        /// </summary>
        internal static string FTPUploadDoneCreateTransferTask {
            get {
                return ResourceManager.GetString("FTPUploadDoneCreateTransferTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In UploadFile function..
        /// </summary>
        internal static string InUploadFile {
            get {
                return ResourceManager.GetString("InUploadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input parameter (null)..
        /// </summary>
        internal static string InvalidInputParameter {
            get {
                return ResourceManager.GetString("InvalidInputParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid upload file request..
        /// </summary>
        internal static string InvalidUploadFileRequest {
            get {
                return ResourceManager.GetString("InvalidUploadFileRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database file config is notr valid.
        /// </summary>
        internal static string LogDataBaseConfigFile {
            get {
                return ResourceManager.GetString("LogDataBaseConfigFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Expiration Date not valid..
        /// </summary>
        internal static string LogDownloadExpirationDateError {
            get {
                return ResourceManager.GetString("LogDownloadExpirationDateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download file list is empty..
        /// </summary>
        internal static string LogDownloadFileListError {
            get {
                return ResourceManager.GetString("LogDownloadFileListError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download folder name is empty.
        /// </summary>
        internal static string LogDownloadFolderEmpty {
            get {
                return ResourceManager.GetString("LogDownloadFolderEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Download FolderPath.
        /// </summary>
        internal static string LogDownloadFolderPath {
            get {
                return ResourceManager.GetString("LogDownloadFolderPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FtpServer directory name is invalid.
        /// </summary>
        internal static string LogDownloadFtpServerDirectoryInvalid {
            get {
                return ResourceManager.GetString("LogDownloadFtpServerDirectoryInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FtpServer Ip value is invalid.
        /// </summary>
        internal static string LogDownloadFtpServerIpInvalid {
            get {
                return ResourceManager.GetString("LogDownloadFtpServerIpInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FtpServer port value is invalid.
        /// </summary>
        internal static string LogDownloadFtpServerPortInvalid {
            get {
                return ResourceManager.GetString("LogDownloadFtpServerPortInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FtpServer password value is invalid.
        /// </summary>
        internal static string LogDownloadFtpServerPwdInvalid {
            get {
                return ResourceManager.GetString("LogDownloadFtpServerPwdInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FtpServer User name is invalid.
        /// </summary>
        internal static string LogDownloadFtpServerUserNameInvalid {
            get {
                return ResourceManager.GetString("LogDownloadFtpServerUserNameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception Context.
        /// </summary>
        internal static string LogExceptionContext {
            get {
                return ResourceManager.GetString("LogExceptionContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local DateTime.
        /// </summary>
        internal static string LogExceptionDateTimeLocal {
            get {
                return ResourceManager.GetString("LogExceptionDateTimeLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UTC DateTime.
        /// </summary>
        internal static string LogExceptionDateTimeUtc {
            get {
                return ResourceManager.GetString("LogExceptionDateTimeUtc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug.
        /// </summary>
        internal static string LogExceptionDebugMessage {
            get {
                return ResourceManager.GetString("LogExceptionDebugMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string LogExceptionErrorMessage {
            get {
                return ResourceManager.GetString("LogExceptionErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception Type.
        /// </summary>
        internal static string LogExceptionExceptionType {
            get {
                return ResourceManager.GetString("LogExceptionExceptionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string LogExceptionInfoMessage {
            get {
                return ResourceManager.GetString("LogExceptionInfoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inner Exception.
        /// </summary>
        internal static string LogExceptionInnerExceptionMessage {
            get {
                return ResourceManager.GetString("LogExceptionInnerExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inner Exception.
        /// </summary>
        internal static string LogExceptionInnerExceptionType {
            get {
                return ResourceManager.GetString("LogExceptionInnerExceptionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception.
        /// </summary>
        internal static string LogExceptionMainExceptionMessage {
            get {
                return ResourceManager.GetString("LogExceptionMainExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stack Trace.
        /// </summary>
        internal static string LogExceptionStackTrace {
            get {
                return ResourceManager.GetString("LogExceptionStackTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T2G Navigation Url could not be found in the configuration file..
        /// </summary>
        internal static string LogExceptionT2G_NotificationUrlNotFound {
            get {
                return ResourceManager.GetString("LogExceptionT2G_NotificationUrlNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T2G Password could not be found in the configuration file..
        /// </summary>
        internal static string LogExceptionT2G_PwdNotFound {
            get {
                return ResourceManager.GetString("LogExceptionT2G_PwdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T2G UserName could not be found in the configuration file..
        /// </summary>
        internal static string LogExceptionT2G_UserNameNotFound {
            get {
                return ResourceManager.GetString("LogExceptionT2G_UserNameNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T2G Application Id could not be found in the configuration file..
        /// </summary>
        internal static string LogExceptionT2GApplicationIdNotFound {
            get {
                return ResourceManager.GetString("LogExceptionT2GApplicationIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thread ID.
        /// </summary>
        internal static string LogExceptionThreadId {
            get {
                return ResourceManager.GetString("LogExceptionThreadId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Thread Name.
        /// </summary>
        internal static string LogExceptionThreadName {
            get {
                return ResourceManager.GetString("LogExceptionThreadName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string LogExceptionWarningrMessage {
            get {
                return ResourceManager.GetString("LogExceptionWarningrMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum message count is not valid.
        /// </summary>
        internal static string LogMaxMessageCountNotValid {
            get {
                return ResourceManager.GetString("LogMaxMessageCountNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum message size is not valid.
        /// </summary>
        internal static string LogMaxMessageSizeNotValid {
            get {
                return ResourceManager.GetString("LogMaxMessageSizeNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input parameter for the OnMessageNotification service is not valid.
        /// </summary>
        internal static string LogNotificationServiceOnMessageParameterNotValid {
            get {
                return ResourceManager.GetString("LogNotificationServiceOnMessageParameterNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input parameter for the OnServiceNotificationservice is not valid.
        /// </summary>
        internal static string LogNotificationServiceOnServiceParameterNotValid {
            get {
                return ResourceManager.GetString("LogNotificationServiceOnServiceParameterNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input parameter for the OnFilePublicationNotification is not valid.
        /// </summary>
        internal static string LogonFilePublicationNotificationParameterNotValid {
            get {
                return ResourceManager.GetString("LogonFilePublicationNotificationParameterNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input parameter for the OnFilesPublishedNotificationis not valid.
        /// </summary>
        internal static string LogonFilesPublishedNotificationParametrNotValid {
            get {
                return ResourceManager.GetString("LogonFilesPublishedNotificationParametrNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input parameter for the OnFilesReceivedNotification is not valid.
        /// </summary>
        internal static string LogonFilesReceivedNotificationParameterNotValid {
            get {
                return ResourceManager.GetString("LogonFilesReceivedNotificationParameterNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input parameter for the OnFileTransferNotification is not valid.
        /// </summary>
        internal static string LogonFileTransferNotificationParameterNotValid {
            get {
                return ResourceManager.GetString("LogonFileTransferNotificationParameterNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PercentageOfMaxNumberOfScheduledMessageToCleanUpInLogDatabase parameter is invalid.
        /// </summary>
        internal static string LogPercentageOfLogToCleanUpInLogDatabase {
            get {
                return ResourceManager.GetString("LogPercentageOfLogToCleanUpInLogDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Id does not exist.
        /// </summary>
        internal static string LogRequestIdNotExist {
            get {
                return ResourceManager.GetString("LogRequestIdNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current service name.
        /// </summary>
        internal static string LogServiceName {
            get {
                return ResourceManager.GetString("LogServiceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SqlServerDataDirectory is empty.
        /// </summary>
        internal static string LogSqlServerDataDirectoryError {
            get {
                return ResourceManager.GetString("LogSqlServerDataDirectoryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Expiration Date not valid..
        /// </summary>
        internal static string LogUploadExpirationDateError {
            get {
                return ResourceManager.GetString("LogUploadExpirationDateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File: {0} is empty.
        /// </summary>
        internal static string LogUploadFileEmpty {
            get {
                return ResourceManager.GetString("LogUploadFileEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload file list is empty..
        /// </summary>
        internal static string LogUploadFileListError {
            get {
                return ResourceManager.GetString("LogUploadFileListError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File: {0} does not exist.
        /// </summary>
        internal static string LogUploadFileNotExists {
            get {
                return ResourceManager.GetString("LogUploadFileNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range for Priority is between 0 to 32.
        /// </summary>
        internal static string LogUploadPriorityError {
            get {
                return ResourceManager.GetString("LogUploadPriorityError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recpient List cannot be empty.
        /// </summary>
        internal static string LogUploadRecpientCountError {
            get {
                return ResourceManager.GetString("LogUploadRecpientCountError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recpient systemId and MissionId cannot be empty.
        /// </summary>
        internal static string LogUploadRecpientSystemIDError {
            get {
                return ResourceManager.GetString("LogUploadRecpientSystemIDError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Id not valid.
        /// </summary>
        internal static string LogUploadRequestIDError {
            get {
                return ResourceManager.GetString("LogUploadRequestIDError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Start Date not valid..
        /// </summary>
        internal static string LogUploadStartDateError {
            get {
                return ResourceManager.GetString("LogUploadStartDateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration date cannot be less than Start Date.
        /// </summary>
        internal static string LogUploadStartDateExpirationDateError {
            get {
                return ResourceManager.GetString("LogUploadStartDateExpirationDateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TimeOut value is not valid..
        /// </summary>
        internal static string LogUserTimeOutValueInvalid {
            get {
                return ResourceManager.GetString("LogUserTimeOutValueInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The configuration parameter &apos;{0}&apos; is missing. Default value &apos;{1}&apos; is used..
        /// </summary>
        internal static string OptionalConfigurationParameterMissing {
            get {
                return ResourceManager.GetString("OptionalConfigurationParameterMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ArgumentOutOfRangeException with FilePath : {0}.
        /// </summary>
        internal static string RemoteFileClassArgumentOutOfRangeException {
            get {
                return ResourceManager.GetString("RemoteFileClassArgumentOutOfRangeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RequestID = {0}, CRCGuid = {1}, Folder ID = {2}, Task ID = {3}.
        /// </summary>
        internal static string RequestAndTaskInfo {
            get {
                return ResourceManager.GetString("RequestAndTaskInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request&apos;s folder expiration date is too soon. .
        /// </summary>
        internal static string RequestFolderExpirationDateNotValid {
            get {
                return ResourceManager.GetString("RequestFolderExpirationDateNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request&apos;s folder expiration date is far enough to use its folder..
        /// </summary>
        internal static string RequestFolderExpirationDateValid {
            get {
                return ResourceManager.GetString("RequestFolderExpirationDateValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request&apos;s folder had problems during data uploading..
        /// </summary>
        internal static string RequestFolderUploadFailed {
            get {
                return ResourceManager.GetString("RequestFolderUploadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RequestID = {0}, CRCGuid = {1}, Folder ID = {2}.
        /// </summary>
        internal static string RequestInfo {
            get {
                return ResourceManager.GetString("RequestInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching in currents requests list..
        /// </summary>
        internal static string SearchingCurrentRequestList {
            get {
                return ResourceManager.GetString("SearchingCurrentRequestList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching directly on T2G Server..
        /// </summary>
        internal static string SearchingT2GServer {
            get {
                return ResourceManager.GetString("SearchingT2GServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following items of the T2G notification message of type {0} are missing or misconfigured: {1}. Please verify the configuration in the T2GVehicleInfo.xml file on the T2G server..
        /// </summary>
        internal static string T2GConverterMissingItemsInNotificationMessageError {
            get {
                return ResourceManager.GetString("T2GConverterMissingItemsInNotificationMessageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload folder creation failed..
        /// </summary>
        internal static string UploadFolderCreationFailed {
            get {
                return ResourceManager.GetString("UploadFolderCreationFailed", resourceCulture);
            }
        }
    }
}
