//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8745
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIS.Ground.RealTime {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Logs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Logs() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RealTime.Logs", typeof(Logs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data of Real-Time service for element &apos;{0}&apos; is temporarily unavailable: {1}..
        /// </summary>
        internal static string DEBUG_GET_SERVICE_DATA_FOR_ELEMENT {
            get {
                return ResourceManager.GetString("DEBUG_GET_SERVICE_DATA_FOR_ELEMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail do get station list for element &apos;{0}&apos;: method &apos;{1}&apos; returned the error &apos;{2}&apos;..
        /// </summary>
        internal static string ERROR_ACCESSING_STATIONLIST_FOR_ELEMENT {
            get {
                return ResourceManager.GetString("ERROR_ACCESSING_STATIONLIST_FOR_ELEMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail to send request to embedded real-time service for element &apos;{0}&apos;..
        /// </summary>
        internal static string ERROR_FAILED_SEND_REQUEST_TO_EMBEDDED {
            get {
                return ResourceManager.GetString("ERROR_FAILED_SEND_REQUEST_TO_EMBEDDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while requesting data of real-time service for element &apos;{0}&apos; : {1}..
        /// </summary>
        internal static string ERROR_GET_SERVICE_DATA_FOR_ELEMENT {
            get {
                return ResourceManager.GetString("ERROR_GET_SERVICE_DATA_FOR_ELEMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to open package LMT version &apos;{0}&apos; for element &apos;{1}&apos;..
        /// </summary>
        internal static string ERROR_RETRIEVESTATIONLIST_CANT_OPEN_PACKAGE {
            get {
                return ResourceManager.GetString("ERROR_RETRIEVESTATIONLIST_CANT_OPEN_PACKAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to find LMT database inside package version {0} for element &apos;{1}&apos;..
        /// </summary>
        internal static string ERROR_RETRIEVESTATIONLIST_LMT_DB_NOT_FOUND {
            get {
                return ResourceManager.GetString("ERROR_RETRIEVESTATIONLIST_LMT_DB_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Embedded LMT version &apos;{0}&apos; not found in RemoteDataStore..
        /// </summary>
        internal static string ERROR_RETRIEVESTATIONLIST_UNKNOWN_EMBEDDED_LMT {
            get {
                return ResourceManager.GetString("ERROR_RETRIEVESTATIONLIST_UNKNOWN_EMBEDDED_LMT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurs when using RemoteDataStoreProxy..
        /// </summary>
        internal static string ERROR_UNKNOWN {
            get {
                return ResourceManager.GetString("ERROR_UNKNOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No elements are currently running mission &apos;{0}&apos;..
        /// </summary>
        internal static string INFO_NO_ELEMENTS_FOR_MISSION {
            get {
                return ResourceManager.GetString("INFO_NO_ELEMENTS_FOR_MISSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     - Update {0} data of mission terminated with result code &apos;{1}&apos;..
        /// </summary>
        internal static string RESULT_PROCESS_MISSION_UPDATE {
            get {
                return ResourceManager.GetString("RESULT_PROCESS_MISSION_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to         Validation of parameter &apos;{0}&apos; failed with message message: {1}.
        ///        Parameter value: &apos;{2}&apos;..
        /// </summary>
        internal static string RESULT_PROCESS_PARAMETER {
            get {
                return ResourceManager.GetString("RESULT_PROCESS_PARAMETER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     - Update {0} data of station &apos;{1}&apos; terminated with result code &apos;{2}&apos;..
        /// </summary>
        internal static string RESULT_PROCESS_STATION_UPDATE {
            get {
                return ResourceManager.GetString("RESULT_PROCESS_STATION_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response of update real-time information from element &apos;{0}&apos; for mission &apos;{1}&apos;:.
        /// </summary>
        internal static string RESULT_PROCESS_TITLE {
            get {
                return ResourceManager.GetString("RESULT_PROCESS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The processing of notification RTPISDataStoreChanged skipped because T2G is offline..
        /// </summary>
        internal static string SKIP_NOTIFICATION_RTPISDATASTORECHANGED_T2G_OFFLINE {
            get {
                return ResourceManager.GetString("SKIP_NOTIFICATION_RTPISDATASTORECHANGED_T2G_OFFLINE", resourceCulture);
            }
        }
    }
}
