//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3623
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataPackageTestClient.DataPackageServiceClient {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetBaselineListResult", Namespace="http://alstom.com/pacis/pis/ground/datapackage")]
    [System.SerializableAttribute()]
    public partial class GetBaselineListResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DataPackageTestClient.DataPackageServiceClient.BaselineDefinition[] baselineDefField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DataPackageTestClient.DataPackageServiceClient.DataPackageErrorEnum error_codeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DataPackageTestClient.DataPackageServiceClient.BaselineDefinition[] baselineDef {
            get {
                return this.baselineDefField;
            }
            set {
                if ((object.ReferenceEquals(this.baselineDefField, value) != true)) {
                    this.baselineDefField = value;
                    this.RaisePropertyChanged("baselineDef");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DataPackageTestClient.DataPackageServiceClient.DataPackageErrorEnum error_code {
            get {
                return this.error_codeField;
            }
            set {
                if ((this.error_codeField.Equals(value) != true)) {
                    this.error_codeField = value;
                    this.RaisePropertyChanged("error_code");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaselineDefinition", Namespace="http://alstom.com/pacis/pis/ground/datapackage/")]
    [System.SerializableAttribute()]
    public partial class BaselineDefinition : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime BaselineCreationDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BaselineDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BaselineVersionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LMTDataPackageVersionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PISBaseDataPackageVersionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PISInfotainmentDataPackageVersionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PISMissionDataPackageVersionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime BaselineCreationDate {
            get {
                return this.BaselineCreationDateField;
            }
            set {
                if ((this.BaselineCreationDateField.Equals(value) != true)) {
                    this.BaselineCreationDateField = value;
                    this.RaisePropertyChanged("BaselineCreationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BaselineDescription {
            get {
                return this.BaselineDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.BaselineDescriptionField, value) != true)) {
                    this.BaselineDescriptionField = value;
                    this.RaisePropertyChanged("BaselineDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BaselineVersion {
            get {
                return this.BaselineVersionField;
            }
            set {
                if ((object.ReferenceEquals(this.BaselineVersionField, value) != true)) {
                    this.BaselineVersionField = value;
                    this.RaisePropertyChanged("BaselineVersion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LMTDataPackageVersion {
            get {
                return this.LMTDataPackageVersionField;
            }
            set {
                if ((object.ReferenceEquals(this.LMTDataPackageVersionField, value) != true)) {
                    this.LMTDataPackageVersionField = value;
                    this.RaisePropertyChanged("LMTDataPackageVersion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PISBaseDataPackageVersion {
            get {
                return this.PISBaseDataPackageVersionField;
            }
            set {
                if ((object.ReferenceEquals(this.PISBaseDataPackageVersionField, value) != true)) {
                    this.PISBaseDataPackageVersionField = value;
                    this.RaisePropertyChanged("PISBaseDataPackageVersion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PISInfotainmentDataPackageVersion {
            get {
                return this.PISInfotainmentDataPackageVersionField;
            }
            set {
                if ((object.ReferenceEquals(this.PISInfotainmentDataPackageVersionField, value) != true)) {
                    this.PISInfotainmentDataPackageVersionField = value;
                    this.RaisePropertyChanged("PISInfotainmentDataPackageVersion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PISMissionDataPackageVersion {
            get {
                return this.PISMissionDataPackageVersionField;
            }
            set {
                if ((object.ReferenceEquals(this.PISMissionDataPackageVersionField, value) != true)) {
                    this.PISMissionDataPackageVersionField = value;
                    this.RaisePropertyChanged("PISMissionDataPackageVersion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataPackageErrorEnum", Namespace="http://alstom.com/pacis/pis/ground/datapackage/")]
    public enum DataPackageErrorEnum : uint {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SUCCESS = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        INVALID_SESSION_ID = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ERROR = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        INVALID_BASELINE_VERSION = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        INVALID_PIS_BASE_DATA_PACKAGE_VERSION = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        INVALID_PIS_MISSION_DATA_PACKAGE_VERSION = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        INVALID_PIS_INFOTAINMENT_DATA_PACKAGE_VERSION = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        INVALID_LMT_DATA_PACKAGE_VERSION = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ELEMENT_ID_NOT_FOUND = 20,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        INVALID_MISSION_ID = 21,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        INVALID_EXPIRATION_DATEANDTIME = 30,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FILE_NOT_FOUND = 40,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        INVALID_PATH = 41,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FILE_CURRENTLY_DOWNLOADING = 42,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        INVALID_TRANSFER_MODE = 50,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        INVALID_TIMEOUT = 51,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TargetAddressType", Namespace="http://alstom.com/pacis/pis/schema/")]
    [System.SerializableAttribute()]
    public partial class TargetAddressType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DataPackageTestClient.DataPackageServiceClient.AddressTypeEnum TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DataPackageTestClient.DataPackageServiceClient.AddressTypeEnum Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddressTypeEnum", Namespace="http://alstom.com/pacis/pis/schema/")]
    public enum AddressTypeEnum : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Element = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MissionOperatorCode = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MissionCode = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetAdresseesDataPackageBaselinesResult", Namespace="http://alstom.com/pacis/pis/ground/datapackage/")]
    [System.SerializableAttribute()]
    public partial class GetAdresseesDataPackageBaselinesResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DataPackageTestClient.DataPackageServiceClient.ElementDescription[] ElementDescField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DataPackageTestClient.DataPackageServiceClient.DataPackageErrorEnum error_codeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DataPackageTestClient.DataPackageServiceClient.ElementDescription[] ElementDesc {
            get {
                return this.ElementDescField;
            }
            set {
                if ((object.ReferenceEquals(this.ElementDescField, value) != true)) {
                    this.ElementDescField = value;
                    this.RaisePropertyChanged("ElementDesc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DataPackageTestClient.DataPackageServiceClient.DataPackageErrorEnum error_code {
            get {
                return this.error_codeField;
            }
            set {
                if ((this.error_codeField.Equals(value) != true)) {
                    this.error_codeField = value;
                    this.RaisePropertyChanged("error_code");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ElementDescription", Namespace="http://alstom.com/pacis/pis/ground/datapackage/")]
    [System.SerializableAttribute()]
    public partial class ElementDescription : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AssignedCurrentBaselineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime AssignedCurrentBaselineExpirationDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AssignedFutureBaselineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime AssignedFutureBaselineActivationDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime AssignedFutureBaselineExpirationDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DataPackageTestClient.DataPackageServiceClient.ElementBaseline ElementArchivedBaselineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ElementArchivedBaselineExpirationDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DataPackageTestClient.DataPackageServiceClient.ElementBaseline ElementCurrentBaselineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ElementCurrentBaselineExpirationDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DataPackageTestClient.DataPackageServiceClient.ElementBaseline ElementFutureBaselineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ElementFutureBaselineActivationDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ElementFutureBaselineExpirationDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ElementIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool isCurrentBaselineForcedField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AssignedCurrentBaseline {
            get {
                return this.AssignedCurrentBaselineField;
            }
            set {
                if ((object.ReferenceEquals(this.AssignedCurrentBaselineField, value) != true)) {
                    this.AssignedCurrentBaselineField = value;
                    this.RaisePropertyChanged("AssignedCurrentBaseline");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime AssignedCurrentBaselineExpirationDate {
            get {
                return this.AssignedCurrentBaselineExpirationDateField;
            }
            set {
                if ((this.AssignedCurrentBaselineExpirationDateField.Equals(value) != true)) {
                    this.AssignedCurrentBaselineExpirationDateField = value;
                    this.RaisePropertyChanged("AssignedCurrentBaselineExpirationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AssignedFutureBaseline {
            get {
                return this.AssignedFutureBaselineField;
            }
            set {
                if ((object.ReferenceEquals(this.AssignedFutureBaselineField, value) != true)) {
                    this.AssignedFutureBaselineField = value;
                    this.RaisePropertyChanged("AssignedFutureBaseline");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime AssignedFutureBaselineActivationDate {
            get {
                return this.AssignedFutureBaselineActivationDateField;
            }
            set {
                if ((this.AssignedFutureBaselineActivationDateField.Equals(value) != true)) {
                    this.AssignedFutureBaselineActivationDateField = value;
                    this.RaisePropertyChanged("AssignedFutureBaselineActivationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime AssignedFutureBaselineExpirationDate {
            get {
                return this.AssignedFutureBaselineExpirationDateField;
            }
            set {
                if ((this.AssignedFutureBaselineExpirationDateField.Equals(value) != true)) {
                    this.AssignedFutureBaselineExpirationDateField = value;
                    this.RaisePropertyChanged("AssignedFutureBaselineExpirationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DataPackageTestClient.DataPackageServiceClient.ElementBaseline ElementArchivedBaseline {
            get {
                return this.ElementArchivedBaselineField;
            }
            set {
                if ((object.ReferenceEquals(this.ElementArchivedBaselineField, value) != true)) {
                    this.ElementArchivedBaselineField = value;
                    this.RaisePropertyChanged("ElementArchivedBaseline");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ElementArchivedBaselineExpirationDate {
            get {
                return this.ElementArchivedBaselineExpirationDateField;
            }
            set {
                if ((this.ElementArchivedBaselineExpirationDateField.Equals(value) != true)) {
                    this.ElementArchivedBaselineExpirationDateField = value;
                    this.RaisePropertyChanged("ElementArchivedBaselineExpirationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DataPackageTestClient.DataPackageServiceClient.ElementBaseline ElementCurrentBaseline {
            get {
                return this.ElementCurrentBaselineField;
            }
            set {
                if ((object.ReferenceEquals(this.ElementCurrentBaselineField, value) != true)) {
                    this.ElementCurrentBaselineField = value;
                    this.RaisePropertyChanged("ElementCurrentBaseline");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ElementCurrentBaselineExpirationDate {
            get {
                return this.ElementCurrentBaselineExpirationDateField;
            }
            set {
                if ((this.ElementCurrentBaselineExpirationDateField.Equals(value) != true)) {
                    this.ElementCurrentBaselineExpirationDateField = value;
                    this.RaisePropertyChanged("ElementCurrentBaselineExpirationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DataPackageTestClient.DataPackageServiceClient.ElementBaseline ElementFutureBaseline {
            get {
                return this.ElementFutureBaselineField;
            }
            set {
                if ((object.ReferenceEquals(this.ElementFutureBaselineField, value) != true)) {
                    this.ElementFutureBaselineField = value;
                    this.RaisePropertyChanged("ElementFutureBaseline");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ElementFutureBaselineActivationDate {
            get {
                return this.ElementFutureBaselineActivationDateField;
            }
            set {
                if ((this.ElementFutureBaselineActivationDateField.Equals(value) != true)) {
                    this.ElementFutureBaselineActivationDateField = value;
                    this.RaisePropertyChanged("ElementFutureBaselineActivationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ElementFutureBaselineExpirationDate {
            get {
                return this.ElementFutureBaselineExpirationDateField;
            }
            set {
                if ((this.ElementFutureBaselineExpirationDateField.Equals(value) != true)) {
                    this.ElementFutureBaselineExpirationDateField = value;
                    this.RaisePropertyChanged("ElementFutureBaselineExpirationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ElementID {
            get {
                return this.ElementIDField;
            }
            set {
                if ((object.ReferenceEquals(this.ElementIDField, value) != true)) {
                    this.ElementIDField = value;
                    this.RaisePropertyChanged("ElementID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isCurrentBaselineForced {
            get {
                return this.isCurrentBaselineForcedField;
            }
            set {
                if ((this.isCurrentBaselineForcedField.Equals(value) != true)) {
                    this.isCurrentBaselineForcedField = value;
                    this.RaisePropertyChanged("isCurrentBaselineForced");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ElementBaseline", Namespace="http://alstom.com/pacis/pis/ground/datapackage/")]
    [System.SerializableAttribute()]
    public partial class ElementBaseline : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BaselineValidityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BaselineVersionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool LMTDataPackageValidityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LMTDataPackageVersionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool PISBaseDataPackageValidityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PISBaseDataPackageVersionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool PISInfotainmentDataPackageValidityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PISInfotainmentDataPackageVersionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool PISMissionDataPackageValidityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PISMissionDataPackageVersionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BaselineValidity {
            get {
                return this.BaselineValidityField;
            }
            set {
                if ((this.BaselineValidityField.Equals(value) != true)) {
                    this.BaselineValidityField = value;
                    this.RaisePropertyChanged("BaselineValidity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BaselineVersion {
            get {
                return this.BaselineVersionField;
            }
            set {
                if ((object.ReferenceEquals(this.BaselineVersionField, value) != true)) {
                    this.BaselineVersionField = value;
                    this.RaisePropertyChanged("BaselineVersion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool LMTDataPackageValidity {
            get {
                return this.LMTDataPackageValidityField;
            }
            set {
                if ((this.LMTDataPackageValidityField.Equals(value) != true)) {
                    this.LMTDataPackageValidityField = value;
                    this.RaisePropertyChanged("LMTDataPackageValidity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LMTDataPackageVersion {
            get {
                return this.LMTDataPackageVersionField;
            }
            set {
                if ((object.ReferenceEquals(this.LMTDataPackageVersionField, value) != true)) {
                    this.LMTDataPackageVersionField = value;
                    this.RaisePropertyChanged("LMTDataPackageVersion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool PISBaseDataPackageValidity {
            get {
                return this.PISBaseDataPackageValidityField;
            }
            set {
                if ((this.PISBaseDataPackageValidityField.Equals(value) != true)) {
                    this.PISBaseDataPackageValidityField = value;
                    this.RaisePropertyChanged("PISBaseDataPackageValidity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PISBaseDataPackageVersion {
            get {
                return this.PISBaseDataPackageVersionField;
            }
            set {
                if ((object.ReferenceEquals(this.PISBaseDataPackageVersionField, value) != true)) {
                    this.PISBaseDataPackageVersionField = value;
                    this.RaisePropertyChanged("PISBaseDataPackageVersion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool PISInfotainmentDataPackageValidity {
            get {
                return this.PISInfotainmentDataPackageValidityField;
            }
            set {
                if ((this.PISInfotainmentDataPackageValidityField.Equals(value) != true)) {
                    this.PISInfotainmentDataPackageValidityField = value;
                    this.RaisePropertyChanged("PISInfotainmentDataPackageValidity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PISInfotainmentDataPackageVersion {
            get {
                return this.PISInfotainmentDataPackageVersionField;
            }
            set {
                if ((object.ReferenceEquals(this.PISInfotainmentDataPackageVersionField, value) != true)) {
                    this.PISInfotainmentDataPackageVersionField = value;
                    this.RaisePropertyChanged("PISInfotainmentDataPackageVersion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool PISMissionDataPackageValidity {
            get {
                return this.PISMissionDataPackageValidityField;
            }
            set {
                if ((this.PISMissionDataPackageValidityField.Equals(value) != true)) {
                    this.PISMissionDataPackageValidityField = value;
                    this.RaisePropertyChanged("PISMissionDataPackageValidity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PISMissionDataPackageVersion {
            get {
                return this.PISMissionDataPackageVersionField;
            }
            set {
                if ((object.ReferenceEquals(this.PISMissionDataPackageVersionField, value) != true)) {
                    this.PISMissionDataPackageVersionField = value;
                    this.RaisePropertyChanged("PISMissionDataPackageVersion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataPackageResult", Namespace="http://alstom.com/pacis/pis/ground/datapackage/")]
    [System.SerializableAttribute()]
    public partial class DataPackageResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DataPackageTestClient.DataPackageServiceClient.DataPackageErrorEnum error_codeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid reqIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DataPackageTestClient.DataPackageServiceClient.DataPackageErrorEnum error_code {
            get {
                return this.error_codeField;
            }
            set {
                if ((this.error_codeField.Equals(value) != true)) {
                    this.error_codeField = value;
                    this.RaisePropertyChanged("error_code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid reqId {
            get {
                return this.reqIdField;
            }
            set {
                if ((this.reqIdField.Equals(value) != true)) {
                    this.reqIdField = value;
                    this.RaisePropertyChanged("reqId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaselineDistributionAttributes", Namespace="http://alstom.com/pacis/pis/ground/datapackage/")]
    [System.SerializableAttribute()]
    public partial class BaselineDistributionAttributes : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DataPackageTestClient.DataPackageServiceClient.FileTransferMode TransferModeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime expirationDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool fileCompressionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private sbyte priorityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime transferDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DataPackageTestClient.DataPackageServiceClient.FileTransferMode TransferMode {
            get {
                return this.TransferModeField;
            }
            set {
                if ((this.TransferModeField.Equals(value) != true)) {
                    this.TransferModeField = value;
                    this.RaisePropertyChanged("TransferMode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime expirationDate {
            get {
                return this.expirationDateField;
            }
            set {
                if ((this.expirationDateField.Equals(value) != true)) {
                    this.expirationDateField = value;
                    this.RaisePropertyChanged("expirationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool fileCompression {
            get {
                return this.fileCompressionField;
            }
            set {
                if ((this.fileCompressionField.Equals(value) != true)) {
                    this.fileCompressionField = value;
                    this.RaisePropertyChanged("fileCompression");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public sbyte priority {
            get {
                return this.priorityField;
            }
            set {
                if ((this.priorityField.Equals(value) != true)) {
                    this.priorityField = value;
                    this.RaisePropertyChanged("priority");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime transferDate {
            get {
                return this.transferDateField;
            }
            set {
                if ((this.transferDateField.Equals(value) != true)) {
                    this.transferDateField = value;
                    this.RaisePropertyChanged("transferDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FileTransferMode", Namespace="http://schemas.datacontract.org/2004/07/PIS.Ground.Core.Data")]
    public enum FileTransferMode : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LowBandwidth = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HighBandwidth = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AnyBandwidth = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ElementAvailableElementDataList", Namespace="http://alstom.com/pacis/pis/schema/", ItemName="AvailableElementData")]
    [System.SerializableAttribute()]
    public class ElementAvailableElementDataList : System.Collections.Generic.List<DataPackageTestClient.DataPackageServiceClient.AvailableElementData> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AvailableElementData", Namespace="http://alstom.com/pacis/pis/schema/")]
    [System.SerializableAttribute()]
    public partial class AvailableElementData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ElementNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LmtPackageVersionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MissionCommercialNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MissionOperatorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool OnlineStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DataPackageTestClient.DataPackageServiceClient.PisBaseline PisBaselineDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PisBasicPackageVersionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ElementNumber {
            get {
                return this.ElementNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ElementNumberField, value) != true)) {
                    this.ElementNumberField = value;
                    this.RaisePropertyChanged("ElementNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LmtPackageVersion {
            get {
                return this.LmtPackageVersionField;
            }
            set {
                if ((object.ReferenceEquals(this.LmtPackageVersionField, value) != true)) {
                    this.LmtPackageVersionField = value;
                    this.RaisePropertyChanged("LmtPackageVersion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MissionCommercialNumber {
            get {
                return this.MissionCommercialNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.MissionCommercialNumberField, value) != true)) {
                    this.MissionCommercialNumberField = value;
                    this.RaisePropertyChanged("MissionCommercialNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MissionOperatorCode {
            get {
                return this.MissionOperatorCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.MissionOperatorCodeField, value) != true)) {
                    this.MissionOperatorCodeField = value;
                    this.RaisePropertyChanged("MissionOperatorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool OnlineStatus {
            get {
                return this.OnlineStatusField;
            }
            set {
                if ((this.OnlineStatusField.Equals(value) != true)) {
                    this.OnlineStatusField = value;
                    this.RaisePropertyChanged("OnlineStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DataPackageTestClient.DataPackageServiceClient.PisBaseline PisBaselineData {
            get {
                return this.PisBaselineDataField;
            }
            set {
                if ((object.ReferenceEquals(this.PisBaselineDataField, value) != true)) {
                    this.PisBaselineDataField = value;
                    this.RaisePropertyChanged("PisBaselineData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PisBasicPackageVersion {
            get {
                return this.PisBasicPackageVersionField;
            }
            set {
                if ((object.ReferenceEquals(this.PisBasicPackageVersionField, value) != true)) {
                    this.PisBasicPackageVersionField = value;
                    this.RaisePropertyChanged("PisBasicPackageVersion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PisBaseline", Namespace="http://alstom.com/pacis/pis/schema/")]
    [System.SerializableAttribute()]
    public partial class PisBaseline : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ArchivedValidOutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ArchivedVersionLmtOutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ArchivedVersionOutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ArchivedVersionPisBaseOutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ArchivedVersionPisInfotainmentOutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ArchivedVersionPisMissionOutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CurrentExpirationDateOutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CurrentForcedOutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CurrentValidOutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CurrentVersionLmtOutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CurrentVersionOutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CurrentVersionPisBaseOutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CurrentVersionPisInfotainmentOutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CurrentVersionPisMissionOutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FutureActivationDateOutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FutureExpirationDateOutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FutureValidOutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FutureVersionLmtOutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FutureVersionOutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FutureVersionPisBaseOutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FutureVersionPisInfotainmentOutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FutureVersionPisMissionOutField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ArchivedValidOut {
            get {
                return this.ArchivedValidOutField;
            }
            set {
                if ((object.ReferenceEquals(this.ArchivedValidOutField, value) != true)) {
                    this.ArchivedValidOutField = value;
                    this.RaisePropertyChanged("ArchivedValidOut");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ArchivedVersionLmtOut {
            get {
                return this.ArchivedVersionLmtOutField;
            }
            set {
                if ((object.ReferenceEquals(this.ArchivedVersionLmtOutField, value) != true)) {
                    this.ArchivedVersionLmtOutField = value;
                    this.RaisePropertyChanged("ArchivedVersionLmtOut");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ArchivedVersionOut {
            get {
                return this.ArchivedVersionOutField;
            }
            set {
                if ((object.ReferenceEquals(this.ArchivedVersionOutField, value) != true)) {
                    this.ArchivedVersionOutField = value;
                    this.RaisePropertyChanged("ArchivedVersionOut");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ArchivedVersionPisBaseOut {
            get {
                return this.ArchivedVersionPisBaseOutField;
            }
            set {
                if ((object.ReferenceEquals(this.ArchivedVersionPisBaseOutField, value) != true)) {
                    this.ArchivedVersionPisBaseOutField = value;
                    this.RaisePropertyChanged("ArchivedVersionPisBaseOut");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ArchivedVersionPisInfotainmentOut {
            get {
                return this.ArchivedVersionPisInfotainmentOutField;
            }
            set {
                if ((object.ReferenceEquals(this.ArchivedVersionPisInfotainmentOutField, value) != true)) {
                    this.ArchivedVersionPisInfotainmentOutField = value;
                    this.RaisePropertyChanged("ArchivedVersionPisInfotainmentOut");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ArchivedVersionPisMissionOut {
            get {
                return this.ArchivedVersionPisMissionOutField;
            }
            set {
                if ((object.ReferenceEquals(this.ArchivedVersionPisMissionOutField, value) != true)) {
                    this.ArchivedVersionPisMissionOutField = value;
                    this.RaisePropertyChanged("ArchivedVersionPisMissionOut");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CurrentExpirationDateOut {
            get {
                return this.CurrentExpirationDateOutField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrentExpirationDateOutField, value) != true)) {
                    this.CurrentExpirationDateOutField = value;
                    this.RaisePropertyChanged("CurrentExpirationDateOut");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CurrentForcedOut {
            get {
                return this.CurrentForcedOutField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrentForcedOutField, value) != true)) {
                    this.CurrentForcedOutField = value;
                    this.RaisePropertyChanged("CurrentForcedOut");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CurrentValidOut {
            get {
                return this.CurrentValidOutField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrentValidOutField, value) != true)) {
                    this.CurrentValidOutField = value;
                    this.RaisePropertyChanged("CurrentValidOut");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CurrentVersionLmtOut {
            get {
                return this.CurrentVersionLmtOutField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrentVersionLmtOutField, value) != true)) {
                    this.CurrentVersionLmtOutField = value;
                    this.RaisePropertyChanged("CurrentVersionLmtOut");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CurrentVersionOut {
            get {
                return this.CurrentVersionOutField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrentVersionOutField, value) != true)) {
                    this.CurrentVersionOutField = value;
                    this.RaisePropertyChanged("CurrentVersionOut");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CurrentVersionPisBaseOut {
            get {
                return this.CurrentVersionPisBaseOutField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrentVersionPisBaseOutField, value) != true)) {
                    this.CurrentVersionPisBaseOutField = value;
                    this.RaisePropertyChanged("CurrentVersionPisBaseOut");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CurrentVersionPisInfotainmentOut {
            get {
                return this.CurrentVersionPisInfotainmentOutField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrentVersionPisInfotainmentOutField, value) != true)) {
                    this.CurrentVersionPisInfotainmentOutField = value;
                    this.RaisePropertyChanged("CurrentVersionPisInfotainmentOut");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CurrentVersionPisMissionOut {
            get {
                return this.CurrentVersionPisMissionOutField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrentVersionPisMissionOutField, value) != true)) {
                    this.CurrentVersionPisMissionOutField = value;
                    this.RaisePropertyChanged("CurrentVersionPisMissionOut");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FutureActivationDateOut {
            get {
                return this.FutureActivationDateOutField;
            }
            set {
                if ((object.ReferenceEquals(this.FutureActivationDateOutField, value) != true)) {
                    this.FutureActivationDateOutField = value;
                    this.RaisePropertyChanged("FutureActivationDateOut");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FutureExpirationDateOut {
            get {
                return this.FutureExpirationDateOutField;
            }
            set {
                if ((object.ReferenceEquals(this.FutureExpirationDateOutField, value) != true)) {
                    this.FutureExpirationDateOutField = value;
                    this.RaisePropertyChanged("FutureExpirationDateOut");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FutureValidOut {
            get {
                return this.FutureValidOutField;
            }
            set {
                if ((object.ReferenceEquals(this.FutureValidOutField, value) != true)) {
                    this.FutureValidOutField = value;
                    this.RaisePropertyChanged("FutureValidOut");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FutureVersionLmtOut {
            get {
                return this.FutureVersionLmtOutField;
            }
            set {
                if ((object.ReferenceEquals(this.FutureVersionLmtOutField, value) != true)) {
                    this.FutureVersionLmtOutField = value;
                    this.RaisePropertyChanged("FutureVersionLmtOut");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FutureVersionOut {
            get {
                return this.FutureVersionOutField;
            }
            set {
                if ((object.ReferenceEquals(this.FutureVersionOutField, value) != true)) {
                    this.FutureVersionOutField = value;
                    this.RaisePropertyChanged("FutureVersionOut");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FutureVersionPisBaseOut {
            get {
                return this.FutureVersionPisBaseOutField;
            }
            set {
                if ((object.ReferenceEquals(this.FutureVersionPisBaseOutField, value) != true)) {
                    this.FutureVersionPisBaseOutField = value;
                    this.RaisePropertyChanged("FutureVersionPisBaseOut");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FutureVersionPisInfotainmentOut {
            get {
                return this.FutureVersionPisInfotainmentOutField;
            }
            set {
                if ((object.ReferenceEquals(this.FutureVersionPisInfotainmentOutField, value) != true)) {
                    this.FutureVersionPisInfotainmentOutField = value;
                    this.RaisePropertyChanged("FutureVersionPisInfotainmentOut");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FutureVersionPisMissionOut {
            get {
                return this.FutureVersionPisMissionOutField;
            }
            set {
                if ((object.ReferenceEquals(this.FutureVersionPisMissionOutField, value) != true)) {
                    this.FutureVersionPisMissionOutField = value;
                    this.RaisePropertyChanged("FutureVersionPisMissionOut");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://alstom.com/pacis/pis/ground/datapackage/", ConfigurationName="DataPackageServiceClient.DataPackageService")]
    public interface DataPackageService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://alstom.com/pacis/pis/ground/datapackage/DataPackageService/getBaselinesLis" +
            "t", ReplyAction="http://alstom.com/pacis/pis/ground/datapackage/DataPackageService/getBaselinesLis" +
            "tResponse")]
        DataPackageTestClient.DataPackageServiceClient.GetBaselineListResult getBaselinesList(System.Guid pSessionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://alstom.com/pacis/pis/ground/datapackage/DataPackageService/getAddresseesDa" +
            "taPackagesBaselines", ReplyAction="http://alstom.com/pacis/pis/ground/datapackage/DataPackageService/getAddresseesDa" +
            "taPackagesBaselinesResponse")]
        DataPackageTestClient.DataPackageServiceClient.GetAdresseesDataPackageBaselinesResult getAddresseesDataPackagesBaselines(System.Guid pSessionId, DataPackageTestClient.DataPackageServiceClient.TargetAddressType pElementAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://alstom.com/pacis/pis/ground/datapackage/DataPackageService/uploadDataPacka" +
            "ges", ReplyAction="http://alstom.com/pacis/pis/ground/datapackage/DataPackageService/uploadDataPacka" +
            "gesResponse")]
        DataPackageTestClient.DataPackageServiceClient.DataPackageResult uploadDataPackages(System.Guid pSessionId, string[] pFilesURLs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://alstom.com/pacis/pis/ground/datapackage/DataPackageService/defineNewBaseli" +
            "ne", ReplyAction="http://alstom.com/pacis/pis/ground/datapackage/DataPackageService/defineNewBaseli" +
            "neResponse")]
        DataPackageTestClient.DataPackageServiceClient.DataPackageResult defineNewBaseline(System.Guid pSessionId, DataPackageTestClient.DataPackageServiceClient.BaselineDefinition pBLDef);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://alstom.com/pacis/pis/ground/datapackage/DataPackageService/assignFutureBas" +
            "elineToElement", ReplyAction="http://alstom.com/pacis/pis/ground/datapackage/DataPackageService/assignFutureBas" +
            "elineToElementResponse")]
        DataPackageTestClient.DataPackageServiceClient.DataPackageResult assignFutureBaselineToElement(System.Guid pSessionId, DataPackageTestClient.DataPackageServiceClient.TargetAddressType pElementAddress, string pBLVersion, System.DateTime pActDate, System.DateTime pExpDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://alstom.com/pacis/pis/ground/datapackage/DataPackageService/assignCurrentBa" +
            "selineToElement", ReplyAction="http://alstom.com/pacis/pis/ground/datapackage/DataPackageService/assignCurrentBa" +
            "selineToElementResponse")]
        DataPackageTestClient.DataPackageServiceClient.DataPackageResult assignCurrentBaselineToElement(System.Guid pSessionId, DataPackageTestClient.DataPackageServiceClient.TargetAddressType pElementAddress, string pBLVersion, System.DateTime pExpDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://alstom.com/pacis/pis/ground/datapackage/DataPackageService/distibuteBaseli" +
            "ne", ReplyAction="http://alstom.com/pacis/pis/ground/datapackage/DataPackageService/distibuteBaseli" +
            "neResponse")]
        DataPackageTestClient.DataPackageServiceClient.DataPackageResult distibuteBaseline(System.Guid pSessionId, DataPackageTestClient.DataPackageServiceClient.TargetAddressType pElementAddress, DataPackageTestClient.DataPackageServiceClient.BaselineDistributionAttributes pBLAttributes, uint pReqTimeout, bool pIncr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://alstom.com/pacis/pis/ground/datapackage/DataPackageService/forceAddressees" +
            "FutureBaseline", ReplyAction="http://alstom.com/pacis/pis/ground/datapackage/DataPackageService/forceAddressees" +
            "FutureBaselineResponse")]
        DataPackageTestClient.DataPackageServiceClient.DataPackageResult forceAddresseesFutureBaseline(System.Guid pSessionId, DataPackageTestClient.DataPackageServiceClient.TargetAddressType pElementAddress, uint pReqTimeout);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://alstom.com/pacis/pis/ground/datapackage/DataPackageService/forceAddressees" +
            "ArchivedBaseline", ReplyAction="http://alstom.com/pacis/pis/ground/datapackage/DataPackageService/forceAddressees" +
            "ArchivedBaselineResponse")]
        DataPackageTestClient.DataPackageServiceClient.DataPackageResult forceAddresseesArchivedBaseline(System.Guid pSessionId, DataPackageTestClient.DataPackageServiceClient.TargetAddressType pElementAddress, uint pReqTimeout);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://alstom.com/pacis/pis/ground/datapackage/DataPackageService/clearAddreesees" +
            "ForcingStatus", ReplyAction="http://alstom.com/pacis/pis/ground/datapackage/DataPackageService/clearAddreesees" +
            "ForcingStatusResponse")]
        DataPackageTestClient.DataPackageServiceClient.DataPackageResult clearAddreeseesForcingStatus(System.Guid pSessionId, DataPackageTestClient.DataPackageServiceClient.TargetAddressType pElementAddress, uint pReqTimeout);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://alstom.com/pacis/pis/ground/datapackage/DataPackageService/GetAvailableEle" +
            "mentDataList", ReplyAction="http://alstom.com/pacis/pis/ground/datapackage/DataPackageService/GetAvailableEle" +
            "mentDataListResponse")]
        DataPackageTestClient.DataPackageServiceClient.DataPackageResult GetAvailableElementDataList(out DataPackageTestClient.DataPackageServiceClient.ElementAvailableElementDataList pElementDataList, System.Guid pSessionId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface DataPackageServiceChannel : DataPackageTestClient.DataPackageServiceClient.DataPackageService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class DataPackageServiceClient : System.ServiceModel.ClientBase<DataPackageTestClient.DataPackageServiceClient.DataPackageService>, DataPackageTestClient.DataPackageServiceClient.DataPackageService {
        
        public DataPackageServiceClient() {
        }
        
        public DataPackageServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DataPackageServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataPackageServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataPackageServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public DataPackageTestClient.DataPackageServiceClient.GetBaselineListResult getBaselinesList(System.Guid pSessionId) {
            return base.Channel.getBaselinesList(pSessionId);
        }
        
        public DataPackageTestClient.DataPackageServiceClient.GetAdresseesDataPackageBaselinesResult getAddresseesDataPackagesBaselines(System.Guid pSessionId, DataPackageTestClient.DataPackageServiceClient.TargetAddressType pElementAddress) {
            return base.Channel.getAddresseesDataPackagesBaselines(pSessionId, pElementAddress);
        }
        
        public DataPackageTestClient.DataPackageServiceClient.DataPackageResult uploadDataPackages(System.Guid pSessionId, string[] pFilesURLs) {
            return base.Channel.uploadDataPackages(pSessionId, pFilesURLs);
        }
        
        public DataPackageTestClient.DataPackageServiceClient.DataPackageResult defineNewBaseline(System.Guid pSessionId, DataPackageTestClient.DataPackageServiceClient.BaselineDefinition pBLDef) {
            return base.Channel.defineNewBaseline(pSessionId, pBLDef);
        }
        
        public DataPackageTestClient.DataPackageServiceClient.DataPackageResult assignFutureBaselineToElement(System.Guid pSessionId, DataPackageTestClient.DataPackageServiceClient.TargetAddressType pElementAddress, string pBLVersion, System.DateTime pActDate, System.DateTime pExpDate) {
            return base.Channel.assignFutureBaselineToElement(pSessionId, pElementAddress, pBLVersion, pActDate, pExpDate);
        }
        
        public DataPackageTestClient.DataPackageServiceClient.DataPackageResult assignCurrentBaselineToElement(System.Guid pSessionId, DataPackageTestClient.DataPackageServiceClient.TargetAddressType pElementAddress, string pBLVersion, System.DateTime pExpDate) {
            return base.Channel.assignCurrentBaselineToElement(pSessionId, pElementAddress, pBLVersion, pExpDate);
        }
        
        public DataPackageTestClient.DataPackageServiceClient.DataPackageResult distibuteBaseline(System.Guid pSessionId, DataPackageTestClient.DataPackageServiceClient.TargetAddressType pElementAddress, DataPackageTestClient.DataPackageServiceClient.BaselineDistributionAttributes pBLAttributes, uint pReqTimeout, bool pIncr) {
            return base.Channel.distibuteBaseline(pSessionId, pElementAddress, pBLAttributes, pReqTimeout, pIncr);
        }
        
        public DataPackageTestClient.DataPackageServiceClient.DataPackageResult forceAddresseesFutureBaseline(System.Guid pSessionId, DataPackageTestClient.DataPackageServiceClient.TargetAddressType pElementAddress, uint pReqTimeout) {
            return base.Channel.forceAddresseesFutureBaseline(pSessionId, pElementAddress, pReqTimeout);
        }
        
        public DataPackageTestClient.DataPackageServiceClient.DataPackageResult forceAddresseesArchivedBaseline(System.Guid pSessionId, DataPackageTestClient.DataPackageServiceClient.TargetAddressType pElementAddress, uint pReqTimeout) {
            return base.Channel.forceAddresseesArchivedBaseline(pSessionId, pElementAddress, pReqTimeout);
        }
        
        public DataPackageTestClient.DataPackageServiceClient.DataPackageResult clearAddreeseesForcingStatus(System.Guid pSessionId, DataPackageTestClient.DataPackageServiceClient.TargetAddressType pElementAddress, uint pReqTimeout) {
            return base.Channel.clearAddreeseesForcingStatus(pSessionId, pElementAddress, pReqTimeout);
        }
        
        public DataPackageTestClient.DataPackageServiceClient.DataPackageResult GetAvailableElementDataList(out DataPackageTestClient.DataPackageServiceClient.ElementAvailableElementDataList pElementDataList, System.Guid pSessionId) {
            return base.Channel.GetAvailableElementDataList(out pElementDataList, pSessionId);
        }
    }
}
