//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :2.0.50727.5485
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIS.Train.Mission
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ActivationMissionCommonInfoType", Namespace="http://alstom.com/pacis/pis/schema/train/mission/")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PIS.Train.Mission.ManualMissionInfoType))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PIS.Train.Mission.ModifiedMissionInfoType))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PIS.Train.Mission.AutomaticMissionInfoType))]
    public partial class ActivationMissionCommonInfoType : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string RequestIdField;
        
        private bool OnboardValidationField;
        
        private string ElementIdField;
        
        private uint MissionIdField;
        
        private string MissionOperatorIdField;
        
        private string MissionStartDateField;
        
        private string LmtDataPackageVersionField;
        
        private PIS.Train.Mission.ActivationMissionCommonInfoType.LanguageCodeListType LanguageCodeListField;
        
        private PIS.Train.Mission.ActivationMissionCommonInfoType.OnboardServiceCodeListType OnboardServiceCodeListField;
        
        private uint CarNumberingOffsetCodeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string RequestId
        {
            get
            {
                return this.RequestIdField;
            }
            set
            {
                this.RequestIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public bool OnboardValidation
        {
            get
            {
                return this.OnboardValidationField;
            }
            set
            {
                this.OnboardValidationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=2)]
        public string ElementId
        {
            get
            {
                return this.ElementIdField;
            }
            set
            {
                this.ElementIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public uint MissionId
        {
            get
            {
                return this.MissionIdField;
            }
            set
            {
                this.MissionIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=4)]
        public string MissionOperatorId
        {
            get
            {
                return this.MissionOperatorIdField;
            }
            set
            {
                this.MissionOperatorIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=5)]
        public string MissionStartDate
        {
            get
            {
                return this.MissionStartDateField;
            }
            set
            {
                this.MissionStartDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=6)]
        public string LmtDataPackageVersion
        {
            get
            {
                return this.LmtDataPackageVersionField;
            }
            set
            {
                this.LmtDataPackageVersionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=7)]
        public PIS.Train.Mission.ActivationMissionCommonInfoType.LanguageCodeListType LanguageCodeList
        {
            get
            {
                return this.LanguageCodeListField;
            }
            set
            {
                this.LanguageCodeListField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=8)]
        public PIS.Train.Mission.ActivationMissionCommonInfoType.OnboardServiceCodeListType OnboardServiceCodeList
        {
            get
            {
                return this.OnboardServiceCodeListField;
            }
            set
            {
                this.OnboardServiceCodeListField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public uint CarNumberingOffsetCode
        {
            get
            {
                return this.CarNumberingOffsetCodeField;
            }
            set
            {
                this.CarNumberingOffsetCodeField = value;
            }
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
        [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ActivationMissionCommonInfoType.LanguageCodeListType", Namespace="http://alstom.com/pacis/pis/schema/train/mission/", ItemName="Code")]
        public class LanguageCodeListType : System.Collections.Generic.List<string>
        {
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
        [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ActivationMissionCommonInfoType.OnboardServiceCodeListType", Namespace="http://alstom.com/pacis/pis/schema/train/mission/", ItemName="Code")]
        public class OnboardServiceCodeListType : System.Collections.Generic.List<uint>
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ManualMissionInfoType", Namespace="http://alstom.com/pacis/pis/schema/train/mission/")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PIS.Train.Mission.ModifiedMissionInfoType))]
    public partial class ManualMissionInfoType : PIS.Train.Mission.ActivationMissionCommonInfoType
    {
        
        private string TrainNameField;
        
        private string MissionTypeField;
        
        private uint RegionCodeField;
        
        private PIS.Train.Mission.ManualMissionInfoType.CommercialNumberListType CommercialNumberListField;
        
        private PIS.Train.Mission.ManualMissionInfoType.StationListType StationListField;
        
        private PIS.Train.Mission.ManualMissionInfoType.StationServiceHourListType StationServiceHourListField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string TrainName
        {
            get
            {
                return this.TrainNameField;
            }
            set
            {
                this.TrainNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=1)]
        public string MissionType
        {
            get
            {
                return this.MissionTypeField;
            }
            set
            {
                this.MissionTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public uint RegionCode
        {
            get
            {
                return this.RegionCodeField;
            }
            set
            {
                this.RegionCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=3)]
        public PIS.Train.Mission.ManualMissionInfoType.CommercialNumberListType CommercialNumberList
        {
            get
            {
                return this.CommercialNumberListField;
            }
            set
            {
                this.CommercialNumberListField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=4)]
        public PIS.Train.Mission.ManualMissionInfoType.StationListType StationList
        {
            get
            {
                return this.StationListField;
            }
            set
            {
                this.StationListField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=5)]
        public PIS.Train.Mission.ManualMissionInfoType.StationServiceHourListType StationServiceHourList
        {
            get
            {
                return this.StationServiceHourListField;
            }
            set
            {
                this.StationServiceHourListField = value;
            }
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
        [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ManualMissionInfoType.CommercialNumberListType", Namespace="http://alstom.com/pacis/pis/schema/train/mission/", ItemName="Number")]
        public class CommercialNumberListType : System.Collections.Generic.List<string>
        {
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
        [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ManualMissionInfoType.StationListType", Namespace="http://alstom.com/pacis/pis/schema/train/mission/", ItemName="Station")]
        public class StationListType : System.Collections.Generic.List<PIS.Train.Mission.StationListType>
        {
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
        [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ManualMissionInfoType.StationServiceHourListType", Namespace="http://alstom.com/pacis/pis/schema/train/mission/", ItemName="ServiceHours")]
        public class StationServiceHourListType : System.Collections.Generic.List<PIS.Train.Mission.StationServiceHoursType>
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ModifiedMissionInfoType", Namespace="http://alstom.com/pacis/pis/schema/train/mission/")]
    public partial class ModifiedMissionInfoType : PIS.Train.Mission.ManualMissionInfoType
    {
        
        private PIS.Train.Mission.StationInsertionType StationInsertionField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public PIS.Train.Mission.StationInsertionType StationInsertion
        {
            get
            {
                return this.StationInsertionField;
            }
            set
            {
                this.StationInsertionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AutomaticMissionInfoType", Namespace="http://alstom.com/pacis/pis/schema/train/mission/")]
    public partial class AutomaticMissionInfoType : PIS.Train.Mission.ActivationMissionCommonInfoType
    {
        
        private PIS.Train.Mission.StationInsertionType StationInsertionField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public PIS.Train.Mission.StationInsertionType StationInsertion
        {
            get
            {
                return this.StationInsertionField;
            }
            set
            {
                this.StationInsertionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StationInsertionType", Namespace="http://alstom.com/pacis/pis/schema/train/mission/")]
    public partial class StationInsertionType : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private uint StationIdField;
        
        private uint TypeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public uint StationId
        {
            get
            {
                return this.StationIdField;
            }
            set
            {
                this.StationIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public uint Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                this.TypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StationListType", Namespace="http://alstom.com/pacis/pis/schema/train/mission/")]
    public partial class StationListType : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private uint IdField;
        
        private string NameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public uint Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StationServiceHoursType", Namespace="http://alstom.com/pacis/pis/schema/train/mission/")]
    public partial class StationServiceHoursType : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ArrivalTimeField;
        
        private string DepartureTimeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ArrivalTime
        {
            get
            {
                return this.ArrivalTimeField;
            }
            set
            {
                this.ArrivalTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string DepartureTime
        {
            get
            {
                return this.DepartureTimeField;
            }
            set
            {
                this.DepartureTimeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultType", Namespace="http://alstom.com/pacis/pis/schema/train/mission/")]
    public enum ResultType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ServiceInhibited = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Failure = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://alstom.com/pacis/pis/train/mission/", ConfigurationName="PIS.Train.Mission.IMissionService")]
    public interface IMissionService
    {
        
        // CODEGEN : La génération du contrat de message depuis l’espace de noms de wrapper (http://alstom.com/pacis/pis/schema/train/mission/) du message ActivateAutomaticModeRequest ne correspond pas à la valeur par défaut (http://alstom.com/pacis/pis/train/mission/)
        [System.ServiceModel.OperationContractAttribute(Action="http://alstom.com/pacis/pis/train/Mission/ActivateAutomaticMode", ReplyAction="*")]
        PIS.Train.Mission.ActivateAutomaticModeResponse ActivateAutomaticMode(PIS.Train.Mission.ActivateAutomaticModeRequest request);
        
        // CODEGEN : La génération du contrat de message depuis l’espace de noms de wrapper (http://alstom.com/pacis/pis/schema/train/mission/) du message ActivateModifiedModeRequest ne correspond pas à la valeur par défaut (http://alstom.com/pacis/pis/train/mission/)
        [System.ServiceModel.OperationContractAttribute(Action="http://alstom.com/pacis/pis/train/Mission/ActivateModifiedMode", ReplyAction="*")]
        PIS.Train.Mission.ActivateModifiedModeResponse ActivateModifiedMode(PIS.Train.Mission.ActivateModifiedModeRequest request);
        
        // CODEGEN : La génération du contrat de message depuis l’espace de noms de wrapper (http://alstom.com/pacis/pis/schema/train/mission/) du message ActivateManualModeRequest ne correspond pas à la valeur par défaut (http://alstom.com/pacis/pis/train/mission/)
        [System.ServiceModel.OperationContractAttribute(Action="http://alstom.com/pacis/pis/train/Mission/ActivateManualMode", ReplyAction="*")]
        PIS.Train.Mission.ActivateManualModeResponse ActivateManualMode(PIS.Train.Mission.ActivateManualModeRequest request);
        
        // CODEGEN : La génération du contrat de message depuis l’espace de noms de wrapper (http://alstom.com/pacis/pis/schema/train/mission/) du message StopMissionRequest ne correspond pas à la valeur par défaut (http://alstom.com/pacis/pis/train/mission/)
        [System.ServiceModel.OperationContractAttribute(Action="http://alstom.com/pacis/pis/train/Mission/StopMission", ReplyAction="*")]
        PIS.Train.Mission.StopMissionResponse StopMission(PIS.Train.Mission.StopMissionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ActivateAutomaticMode", WrapperNamespace="http://alstom.com/pacis/pis/schema/train/mission/", IsWrapped=true)]
    public partial class ActivateAutomaticModeRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://alstom.com/pacis/pis/schema/train/mission/", Order=0)]
        public PIS.Train.Mission.AutomaticMissionInfoType MissionInfo;
        
        public ActivateAutomaticModeRequest()
        {
        }
        
        public ActivateAutomaticModeRequest(PIS.Train.Mission.AutomaticMissionInfoType MissionInfo)
        {
            this.MissionInfo = MissionInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ActivateAutomaticModeResponse", WrapperNamespace="http://alstom.com/pacis/pis/schema/train/mission/", IsWrapped=true)]
    public partial class ActivateAutomaticModeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://alstom.com/pacis/pis/schema/train/mission/", Order=0)]
        public PIS.Train.Mission.ResultType Result;
        
        public ActivateAutomaticModeResponse()
        {
        }
        
        public ActivateAutomaticModeResponse(PIS.Train.Mission.ResultType Result)
        {
            this.Result = Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ActivateModifiedMode", WrapperNamespace="http://alstom.com/pacis/pis/schema/train/mission/", IsWrapped=true)]
    public partial class ActivateModifiedModeRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://alstom.com/pacis/pis/schema/train/mission/", Order=0)]
        public PIS.Train.Mission.ModifiedMissionInfoType MissionInfo;
        
        public ActivateModifiedModeRequest()
        {
        }
        
        public ActivateModifiedModeRequest(PIS.Train.Mission.ModifiedMissionInfoType MissionInfo)
        {
            this.MissionInfo = MissionInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ActivateModifiedModeResponse", WrapperNamespace="http://alstom.com/pacis/pis/schema/train/mission/", IsWrapped=true)]
    public partial class ActivateModifiedModeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://alstom.com/pacis/pis/schema/train/mission/", Order=0)]
        public PIS.Train.Mission.ResultType Result;
        
        public ActivateModifiedModeResponse()
        {
        }
        
        public ActivateModifiedModeResponse(PIS.Train.Mission.ResultType Result)
        {
            this.Result = Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ActivateManualMode", WrapperNamespace="http://alstom.com/pacis/pis/schema/train/mission/", IsWrapped=true)]
    public partial class ActivateManualModeRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://alstom.com/pacis/pis/schema/train/mission/", Order=0)]
        public PIS.Train.Mission.ManualMissionInfoType MissionInfo;
        
        public ActivateManualModeRequest()
        {
        }
        
        public ActivateManualModeRequest(PIS.Train.Mission.ManualMissionInfoType MissionInfo)
        {
            this.MissionInfo = MissionInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ActivateManualModeResponse", WrapperNamespace="http://alstom.com/pacis/pis/schema/train/mission/", IsWrapped=true)]
    public partial class ActivateManualModeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://alstom.com/pacis/pis/schema/train/mission/", Order=0)]
        public PIS.Train.Mission.ResultType Result;
        
        public ActivateManualModeResponse()
        {
        }
        
        public ActivateManualModeResponse(PIS.Train.Mission.ResultType Result)
        {
            this.Result = Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="StopMission", WrapperNamespace="http://alstom.com/pacis/pis/schema/train/mission/", IsWrapped=true)]
    public partial class StopMissionRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://alstom.com/pacis/pis/schema/train/mission/", Order=0)]
        public string RequestId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://alstom.com/pacis/pis/schema/train/mission/", Order=1)]
        public string ElementId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://alstom.com/pacis/pis/schema/train/mission/", Order=2)]
        public string MissionOperatorId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://alstom.com/pacis/pis/schema/train/mission/", Order=3)]
        public bool OnboardValidation;
        
        public StopMissionRequest()
        {
        }
        
        public StopMissionRequest(string RequestId, string ElementId, string MissionOperatorId, bool OnboardValidation)
        {
            this.RequestId = RequestId;
            this.ElementId = ElementId;
            this.MissionOperatorId = MissionOperatorId;
            this.OnboardValidation = OnboardValidation;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="StopMissionResponse", WrapperNamespace="http://alstom.com/pacis/pis/schema/train/mission/", IsWrapped=true)]
    public partial class StopMissionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://alstom.com/pacis/pis/schema/train/mission/", Order=0)]
        public PIS.Train.Mission.ResultType Result;
        
        public StopMissionResponse()
        {
        }
        
        public StopMissionResponse(PIS.Train.Mission.ResultType Result)
        {
            this.Result = Result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IMissionServiceChannel : PIS.Train.Mission.IMissionService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class MissionServiceClient : System.ServiceModel.ClientBase<PIS.Train.Mission.IMissionService>, PIS.Train.Mission.IMissionService
    {
        
        public MissionServiceClient()
        {
        }
        
        public MissionServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public MissionServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public MissionServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public MissionServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PIS.Train.Mission.ActivateAutomaticModeResponse PIS.Train.Mission.IMissionService.ActivateAutomaticMode(PIS.Train.Mission.ActivateAutomaticModeRequest request)
        {
            return base.Channel.ActivateAutomaticMode(request);
        }
        
        public PIS.Train.Mission.ResultType ActivateAutomaticMode(PIS.Train.Mission.AutomaticMissionInfoType MissionInfo)
        {
            PIS.Train.Mission.ActivateAutomaticModeRequest inValue = new PIS.Train.Mission.ActivateAutomaticModeRequest();
            inValue.MissionInfo = MissionInfo;
            PIS.Train.Mission.ActivateAutomaticModeResponse retVal = ((PIS.Train.Mission.IMissionService)(this)).ActivateAutomaticMode(inValue);
            return retVal.Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PIS.Train.Mission.ActivateModifiedModeResponse PIS.Train.Mission.IMissionService.ActivateModifiedMode(PIS.Train.Mission.ActivateModifiedModeRequest request)
        {
            return base.Channel.ActivateModifiedMode(request);
        }
        
        public PIS.Train.Mission.ResultType ActivateModifiedMode(PIS.Train.Mission.ModifiedMissionInfoType MissionInfo)
        {
            PIS.Train.Mission.ActivateModifiedModeRequest inValue = new PIS.Train.Mission.ActivateModifiedModeRequest();
            inValue.MissionInfo = MissionInfo;
            PIS.Train.Mission.ActivateModifiedModeResponse retVal = ((PIS.Train.Mission.IMissionService)(this)).ActivateModifiedMode(inValue);
            return retVal.Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PIS.Train.Mission.ActivateManualModeResponse PIS.Train.Mission.IMissionService.ActivateManualMode(PIS.Train.Mission.ActivateManualModeRequest request)
        {
            return base.Channel.ActivateManualMode(request);
        }
        
        public PIS.Train.Mission.ResultType ActivateManualMode(PIS.Train.Mission.ManualMissionInfoType MissionInfo)
        {
            PIS.Train.Mission.ActivateManualModeRequest inValue = new PIS.Train.Mission.ActivateManualModeRequest();
            inValue.MissionInfo = MissionInfo;
            PIS.Train.Mission.ActivateManualModeResponse retVal = ((PIS.Train.Mission.IMissionService)(this)).ActivateManualMode(inValue);
            return retVal.Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PIS.Train.Mission.StopMissionResponse PIS.Train.Mission.IMissionService.StopMission(PIS.Train.Mission.StopMissionRequest request)
        {
            return base.Channel.StopMission(request);
        }
        
        public PIS.Train.Mission.ResultType StopMission(string RequestId, string ElementId, string MissionOperatorId, bool OnboardValidation)
        {
            PIS.Train.Mission.StopMissionRequest inValue = new PIS.Train.Mission.StopMissionRequest();
            inValue.RequestId = RequestId;
            inValue.ElementId = ElementId;
            inValue.MissionOperatorId = MissionOperatorId;
            inValue.OnboardValidation = OnboardValidation;
            PIS.Train.Mission.StopMissionResponse retVal = ((PIS.Train.Mission.IMissionService)(this)).StopMission(inValue);
            return retVal.Result;
        }
    }
}
