//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :2.0.50727.5485
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIS.Ground.DataPackage
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://alstom.com/pacis/pis/train/datapackage/", ConfigurationName="PIS.Ground.DataPackage.IDataPackageTrainService")]
    public interface IDataPackageTrainService
    {
        
        // CODEGEN : La génération du contrat de message depuis l’espace de noms de wrapper (http://alstom.com/pacis/pis/schema/) du message ForceFutureBaselineRequest ne correspond pas à la valeur par défaut (http://alstom.com/pacis/pis/train/datapackage/)
        [System.ServiceModel.OperationContractAttribute(Action="http://alstom.com/pacis/pis/train/datapackage/ForceFutureBaseline", ReplyAction="*")]
        PIS.Ground.DataPackage.ForceFutureBaselineResponse ForceFutureBaseline(PIS.Ground.DataPackage.ForceFutureBaselineRequest request);
        
        // CODEGEN : La génération du contrat de message depuis l’espace de noms de wrapper (http://alstom.com/pacis/pis/schema/) du message ForceArchivedBaselineRequest ne correspond pas à la valeur par défaut (http://alstom.com/pacis/pis/train/datapackage/)
        [System.ServiceModel.OperationContractAttribute(Action="http://alstom.com/pacis/pis/train/datapackage/ForceArchivedBaseline", ReplyAction="*")]
        PIS.Ground.DataPackage.ForceArchivedBaselineResponse ForceArchivedBaseline(PIS.Ground.DataPackage.ForceArchivedBaselineRequest request);
        
        // CODEGEN : La génération du contrat de message depuis l’espace de noms de wrapper (http://alstom.com/pacis/pis/schema/) du message CancelBaselineForcingRequest ne correspond pas à la valeur par défaut (http://alstom.com/pacis/pis/train/datapackage/)
        [System.ServiceModel.OperationContractAttribute(Action="http://alstom.com/pacis/pis/train/datapackage/CancelBaselineForcing", ReplyAction="*")]
        PIS.Ground.DataPackage.CancelBaselineForcingResponse CancelBaselineForcing(PIS.Ground.DataPackage.CancelBaselineForcingRequest request);
        
        // CODEGEN : La génération du contrat de message depuis l’espace de noms de wrapper (http://alstom.com/pacis/pis/schema/) du message SetBaselineVersionRequest ne correspond pas à la valeur par défaut (http://alstom.com/pacis/pis/train/datapackage/)
        [System.ServiceModel.OperationContractAttribute(Action="http://alstom.com/pacis/pis/train/datapackage/SetBaselineVersion", ReplyAction="*")]
        PIS.Ground.DataPackage.SetBaselineVersionResponse SetBaselineVersion(PIS.Ground.DataPackage.SetBaselineVersionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ForceFutureBaseline", WrapperNamespace="http://alstom.com/pacis/pis/schema/", IsWrapped=true)]
    public partial class ForceFutureBaselineRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string RequestId;
        
        public ForceFutureBaselineRequest()
        {
        }
        
        public ForceFutureBaselineRequest(string RequestId)
        {
            this.RequestId = RequestId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ForceFutureBaselineResponse", WrapperNamespace="http://alstom.com/pacis/pis/schema/", IsWrapped=true)]
    public partial class ForceFutureBaselineResponse
    {
        
        public ForceFutureBaselineResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ForceArchivedBaseline", WrapperNamespace="http://alstom.com/pacis/pis/schema/", IsWrapped=true)]
    public partial class ForceArchivedBaselineRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string RequestId;
        
        public ForceArchivedBaselineRequest()
        {
        }
        
        public ForceArchivedBaselineRequest(string RequestId)
        {
            this.RequestId = RequestId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ForceArchivedBaselineResponse", WrapperNamespace="http://alstom.com/pacis/pis/schema/", IsWrapped=true)]
    public partial class ForceArchivedBaselineResponse
    {
        
        public ForceArchivedBaselineResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CancelBaselineForcing", WrapperNamespace="http://alstom.com/pacis/pis/schema/", IsWrapped=true)]
    public partial class CancelBaselineForcingRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string RequestId;
        
        public CancelBaselineForcingRequest()
        {
        }
        
        public CancelBaselineForcingRequest(string RequestId)
        {
            this.RequestId = RequestId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CancelBaselineForcingResponse", WrapperNamespace="http://alstom.com/pacis/pis/schema/", IsWrapped=true)]
    public partial class CancelBaselineForcingResponse
    {
        
        public CancelBaselineForcingResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetBaselineVersion", WrapperNamespace="http://alstom.com/pacis/pis/schema/", IsWrapped=true)]
    public partial class SetBaselineVersionRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string RequestId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string BaselineVersion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string PisBaseVersion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string PisMissionVersion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string PisInfotainmentVersion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string LmtVersion;
        
        public SetBaselineVersionRequest()
        {
        }
        
        public SetBaselineVersionRequest(string RequestId, string BaselineVersion, string PisBaseVersion, string PisMissionVersion, string PisInfotainmentVersion, string LmtVersion)
        {
            this.RequestId = RequestId;
            this.BaselineVersion = BaselineVersion;
            this.PisBaseVersion = PisBaseVersion;
            this.PisMissionVersion = PisMissionVersion;
            this.PisInfotainmentVersion = PisInfotainmentVersion;
            this.LmtVersion = LmtVersion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetBaselineVersionResponse", WrapperNamespace="http://alstom.com/pacis/pis/schema/", IsWrapped=true)]
    public partial class SetBaselineVersionResponse
    {
        
        public SetBaselineVersionResponse()
        {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IDataPackageTrainServiceChannel : PIS.Ground.DataPackage.IDataPackageTrainService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class DataPackageTrainServiceClient : System.ServiceModel.ClientBase<PIS.Ground.DataPackage.IDataPackageTrainService>, PIS.Ground.DataPackage.IDataPackageTrainService
    {
        
        public DataPackageTrainServiceClient()
        {
        }
        
        public DataPackageTrainServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public DataPackageTrainServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public DataPackageTrainServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public DataPackageTrainServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PIS.Ground.DataPackage.ForceFutureBaselineResponse PIS.Ground.DataPackage.IDataPackageTrainService.ForceFutureBaseline(PIS.Ground.DataPackage.ForceFutureBaselineRequest request)
        {
            return base.Channel.ForceFutureBaseline(request);
        }
        
        public void ForceFutureBaseline(string RequestId)
        {
            PIS.Ground.DataPackage.ForceFutureBaselineRequest inValue = new PIS.Ground.DataPackage.ForceFutureBaselineRequest();
            inValue.RequestId = RequestId;
            PIS.Ground.DataPackage.ForceFutureBaselineResponse retVal = ((PIS.Ground.DataPackage.IDataPackageTrainService)(this)).ForceFutureBaseline(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PIS.Ground.DataPackage.ForceArchivedBaselineResponse PIS.Ground.DataPackage.IDataPackageTrainService.ForceArchivedBaseline(PIS.Ground.DataPackage.ForceArchivedBaselineRequest request)
        {
            return base.Channel.ForceArchivedBaseline(request);
        }
        
        public void ForceArchivedBaseline(string RequestId)
        {
            PIS.Ground.DataPackage.ForceArchivedBaselineRequest inValue = new PIS.Ground.DataPackage.ForceArchivedBaselineRequest();
            inValue.RequestId = RequestId;
            PIS.Ground.DataPackage.ForceArchivedBaselineResponse retVal = ((PIS.Ground.DataPackage.IDataPackageTrainService)(this)).ForceArchivedBaseline(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PIS.Ground.DataPackage.CancelBaselineForcingResponse PIS.Ground.DataPackage.IDataPackageTrainService.CancelBaselineForcing(PIS.Ground.DataPackage.CancelBaselineForcingRequest request)
        {
            return base.Channel.CancelBaselineForcing(request);
        }
        
        public void CancelBaselineForcing(string RequestId)
        {
            PIS.Ground.DataPackage.CancelBaselineForcingRequest inValue = new PIS.Ground.DataPackage.CancelBaselineForcingRequest();
            inValue.RequestId = RequestId;
            PIS.Ground.DataPackage.CancelBaselineForcingResponse retVal = ((PIS.Ground.DataPackage.IDataPackageTrainService)(this)).CancelBaselineForcing(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PIS.Ground.DataPackage.SetBaselineVersionResponse PIS.Ground.DataPackage.IDataPackageTrainService.SetBaselineVersion(PIS.Ground.DataPackage.SetBaselineVersionRequest request)
        {
            return base.Channel.SetBaselineVersion(request);
        }
        
        public void SetBaselineVersion(string RequestId, string BaselineVersion, string PisBaseVersion, string PisMissionVersion, string PisInfotainmentVersion, string LmtVersion)
        {
            PIS.Ground.DataPackage.SetBaselineVersionRequest inValue = new PIS.Ground.DataPackage.SetBaselineVersionRequest();
            inValue.RequestId = RequestId;
            inValue.BaselineVersion = BaselineVersion;
            inValue.PisBaseVersion = PisBaseVersion;
            inValue.PisMissionVersion = PisMissionVersion;
            inValue.PisInfotainmentVersion = PisInfotainmentVersion;
            inValue.LmtVersion = LmtVersion;
            PIS.Ground.DataPackage.SetBaselineVersionResponse retVal = ((PIS.Ground.DataPackage.IDataPackageTrainService)(this)).SetBaselineVersion(inValue);
        }
    }
}
