//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3625
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIS.Ground.RemoteDataStore.RemoteDataStoreCallbackClient {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StatusEnum", Namespace="http://schemas.datacontract.org/2004/07/PIS.Ground.RemoteDataStore")]
    public enum StatusEnum : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PROCESSING = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ALREADY_EXISTS = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        COMPLETED = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FAILED = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WAITING_TO_TRANSFER = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TRANSFERRING = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TRANSFERRED = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TIME_OUT = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FAILED_DATA_PACKAGE_MISSING = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FAILED_UNKNOW_ONBOARD_DATA_PACKAGE = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FAILED_NO_ASSIGNED_FUTURE_BASELINE = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FAILED_TRANSFER_CANCELLED_MANUALY = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FAILED_REJECTED_BY_ELEMENT = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        INHIBITED = 13,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OpenDataPackageResult", Namespace="http://schemas.datacontract.org/2004/07/PIS.Ground.RemoteDataStore")]
    [System.SerializableAttribute()]
    public partial class OpenDataPackageResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocalPackagePathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PIS.Ground.RemoteDataStore.RemoteDataStoreCallbackClient.OpenDataPackageStatusEnum StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LocalPackagePath {
            get {
                return this.LocalPackagePathField;
            }
            set {
                if ((object.ReferenceEquals(this.LocalPackagePathField, value) != true)) {
                    this.LocalPackagePathField = value;
                    this.RaisePropertyChanged("LocalPackagePath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PIS.Ground.RemoteDataStore.RemoteDataStoreCallbackClient.OpenDataPackageStatusEnum Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OpenDataPackageStatusEnum", Namespace="http://schemas.datacontract.org/2004/07/PIS.Ground.RemoteDataStore")]
    public enum OpenDataPackageStatusEnum : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        COMPLETED = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FAILED_UNKNOWN_PACKAGE = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RemoteDataStoreCallbackClient.IRemoteDataStoreCallback")]
    public interface IRemoteDataStoreCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IRemoteDataStoreCallback/updateBaselineDefinitionStatus")]
        void updateBaselineDefinitionStatus(System.Guid pReqID, string pBLVersion, PIS.Ground.RemoteDataStore.RemoteDataStoreCallbackClient.StatusEnum pStatus);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IRemoteDataStoreCallback/missingDataPackageNotification")]
        void missingDataPackageNotification(System.Guid pReqID, string[] pDPCharsList);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IRemoteDataStoreCallback/updatePackageUploadStatus")]
        void updatePackageUploadStatus(System.Guid pReqID, PIS.Ground.RemoteDataStore.RemoteDataStoreCallbackClient.StatusEnum pStatus);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IRemoteDataStoreCallback/updateBaselineAssignmentStatus")]
        void updateBaselineAssignmentStatus(System.Guid pReqID, PIS.Ground.RemoteDataStore.RemoteDataStoreCallbackClient.StatusEnum pStatus);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IRemoteDataStoreCallback/updatePackageDistributionStatus")]
        void updatePackageDistributionStatus(System.Guid pReqID, string pEID, PIS.Ground.RemoteDataStore.RemoteDataStoreCallbackClient.StatusEnum pStatus);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IRemoteDataStoreCallback/futureBaselineDefinitionNotification")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PIS.Ground.RemoteDataStore.RemoteDataStoreCallbackClient.StatusEnum))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PIS.Ground.RemoteDataStore.RemoteDataStoreCallbackClient.OpenDataPackageResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PIS.Ground.RemoteDataStore.RemoteDataStoreCallbackClient.OpenDataPackageStatusEnum))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(string[]))]
        void futureBaselineDefinitionNotification(System.Guid pReqID, string pEID, object pFBaseline);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IRemoteDataStoreCallback/updateOpenLocalDataPackageStatus")]
        void updateOpenLocalDataPackageStatus(System.Guid pReqID, string pElementId, PIS.Ground.RemoteDataStore.RemoteDataStoreCallbackClient.OpenDataPackageResult pResult);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IRemoteDataStoreCallbackChannel : PIS.Ground.RemoteDataStore.RemoteDataStoreCallbackClient.IRemoteDataStoreCallback, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class RemoteDataStoreCallbackClient : System.ServiceModel.ClientBase<PIS.Ground.RemoteDataStore.RemoteDataStoreCallbackClient.IRemoteDataStoreCallback>, PIS.Ground.RemoteDataStore.RemoteDataStoreCallbackClient.IRemoteDataStoreCallback {
        
        public RemoteDataStoreCallbackClient() {
        }
        
        public RemoteDataStoreCallbackClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RemoteDataStoreCallbackClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RemoteDataStoreCallbackClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RemoteDataStoreCallbackClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void updateBaselineDefinitionStatus(System.Guid pReqID, string pBLVersion, PIS.Ground.RemoteDataStore.RemoteDataStoreCallbackClient.StatusEnum pStatus) {
            base.Channel.updateBaselineDefinitionStatus(pReqID, pBLVersion, pStatus);
        }
        
        public void missingDataPackageNotification(System.Guid pReqID, string[] pDPCharsList) {
            base.Channel.missingDataPackageNotification(pReqID, pDPCharsList);
        }
        
        public void updatePackageUploadStatus(System.Guid pReqID, PIS.Ground.RemoteDataStore.RemoteDataStoreCallbackClient.StatusEnum pStatus) {
            base.Channel.updatePackageUploadStatus(pReqID, pStatus);
        }
        
        public void updateBaselineAssignmentStatus(System.Guid pReqID, PIS.Ground.RemoteDataStore.RemoteDataStoreCallbackClient.StatusEnum pStatus) {
            base.Channel.updateBaselineAssignmentStatus(pReqID, pStatus);
        }
        
        public void updatePackageDistributionStatus(System.Guid pReqID, string pEID, PIS.Ground.RemoteDataStore.RemoteDataStoreCallbackClient.StatusEnum pStatus) {
            base.Channel.updatePackageDistributionStatus(pReqID, pEID, pStatus);
        }
        
        public void futureBaselineDefinitionNotification(System.Guid pReqID, string pEID, object pFBaseline) {
            base.Channel.futureBaselineDefinitionNotification(pReqID, pEID, pFBaseline);
        }
        
        public void updateOpenLocalDataPackageStatus(System.Guid pReqID, string pElementId, PIS.Ground.RemoteDataStore.RemoteDataStoreCallbackClient.OpenDataPackageResult pResult) {
            base.Channel.updateOpenLocalDataPackageStatus(pReqID, pElementId, pResult);
        }
    }
}
