//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :2.0.50727.5485
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIS.Train.RealTime
{
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ActionTypeEnum", Namespace="http://alstom.com/pacis/pis/schema/realtimecommon/")]
    public enum ActionTypeEnum : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Set = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Update = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Delete = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DelayType", Namespace="http://alstom.com/pacis/pis/schema/realtimecommon/")]
    public partial class DelayType : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private uint AgeField;
        
        private uint DelayValueField;
        
        private string DelayReasonField;
        
        private int DelayReasonCodeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public uint Age
        {
            get
            {
                return this.AgeField;
            }
            set
            {
                this.AgeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public uint DelayValue
        {
            get
            {
                return this.DelayValueField;
            }
            set
            {
                this.DelayValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string DelayReason
        {
            get
            {
                return this.DelayReasonField;
            }
            set
            {
                this.DelayReasonField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int DelayReasonCode
        {
            get
            {
                return this.DelayReasonCodeField;
            }
            set
            {
                this.DelayReasonCodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WeatherType", Namespace="http://alstom.com/pacis/pis/schema/realtimecommon/")]
    public partial class WeatherType : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private uint AgeField;
        
        private string WeatherConditionField;
        
        private int WeatherConditionCodeField;
        
        private string TemperatureInCentigradeField;
        
        private string TemperatureInFahrenheitField;
        
        private string HumidityField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public uint Age
        {
            get
            {
                return this.AgeField;
            }
            set
            {
                this.AgeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string WeatherCondition
        {
            get
            {
                return this.WeatherConditionField;
            }
            set
            {
                this.WeatherConditionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int WeatherConditionCode
        {
            get
            {
                return this.WeatherConditionCodeField;
            }
            set
            {
                this.WeatherConditionCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string TemperatureInCentigrade
        {
            get
            {
                return this.TemperatureInCentigradeField;
            }
            set
            {
                this.TemperatureInCentigradeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string TemperatureInFahrenheit
        {
            get
            {
                return this.TemperatureInFahrenheitField;
            }
            set
            {
                this.TemperatureInFahrenheitField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Humidity
        {
            get
            {
                return this.HumidityField;
            }
            set
            {
                this.HumidityField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ListOfResultType", Namespace="http://alstom.com/pacis/pis/schema/realtimecommon/", ItemName="Result")]
    public class ListOfResultType : System.Collections.Generic.List<PIS.Train.RealTime.ResultType>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultType", Namespace="http://alstom.com/pacis/pis/schema/realtimecommon/")]
    public partial class ResultType : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private PIS.Train.RealTime.ResultCodeEnum ResultCodeField;
        
        private PIS.Train.RealTime.InformationTypeEnum InformationTypeField;
        
        private string MissionCodeField;
        
        private string StationCodeField;
        
        private PIS.Train.RealTime.ListOfComplexErrorType ComplexErrorListField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public PIS.Train.RealTime.ResultCodeEnum ResultCode
        {
            get
            {
                return this.ResultCodeField;
            }
            set
            {
                this.ResultCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public PIS.Train.RealTime.InformationTypeEnum InformationType
        {
            get
            {
                return this.InformationTypeField;
            }
            set
            {
                this.InformationTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string MissionCode
        {
            get
            {
                return this.MissionCodeField;
            }
            set
            {
                this.MissionCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string StationCode
        {
            get
            {
                return this.StationCodeField;
            }
            set
            {
                this.StationCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public PIS.Train.RealTime.ListOfComplexErrorType ComplexErrorList
        {
            get
            {
                return this.ComplexErrorListField;
            }
            set
            {
                this.ComplexErrorListField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultCodeEnum", Namespace="http://alstom.com/pacis/pis/schema/realtimecommon/")]
    public enum ResultCodeEnum : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OK = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotCurrentMission = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        StationNotInTrainRoute = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ComplexError = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InformationTypeEnum", Namespace="http://alstom.com/pacis/pis/schema/realtimecommon/")]
    public enum InformationTypeEnum : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Connection = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Delay = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Platform = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Weather = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ListOfComplexErrorType", Namespace="http://alstom.com/pacis/pis/schema/realtimecommon/", ItemName="ComplexError")]
    public class ListOfComplexErrorType : System.Collections.Generic.List<PIS.Train.RealTime.ComplexErrorType>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ComplexErrorType", Namespace="http://alstom.com/pacis/pis/schema/realtimecommon/")]
    public partial class ComplexErrorType : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private PIS.Train.RealTime.ListOfParameterErrorType ParameterErrorListField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public PIS.Train.RealTime.ListOfParameterErrorType ParameterErrorList
        {
            get
            {
                return this.ParameterErrorListField;
            }
            set
            {
                this.ParameterErrorListField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ListOfParameterErrorType", Namespace="http://alstom.com/pacis/pis/schema/realtimecommon/", ItemName="ParameterError")]
    public class ListOfParameterErrorType : System.Collections.Generic.List<PIS.Train.RealTime.ParameterErrorType>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ParameterErrorType", Namespace="http://alstom.com/pacis/pis/schema/realtimecommon/")]
    public partial class ParameterErrorType : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ParameterNameField;
        
        private string ErrorMessageField;
        
        private string ErroneousValueField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string ParameterName
        {
            get
            {
                return this.ParameterNameField;
            }
            set
            {
                this.ParameterNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=1)]
        public string ErrorMessage
        {
            get
            {
                return this.ErrorMessageField;
            }
            set
            {
                this.ErrorMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=2)]
        public string ErroneousValue
        {
            get
            {
                return this.ErroneousValueField;
            }
            set
            {
                this.ErroneousValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ListOfStationDataType", Namespace="http://alstom.com/pacis/pis/schema/realtimecommon/", ItemName="StationData")]
    public class ListOfStationDataType : System.Collections.Generic.List<PIS.Train.RealTime.StationDataType>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StationDataType", Namespace="http://alstom.com/pacis/pis/schema/realtimecommon/")]
    public partial class StationDataType : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string StationCodeField;
        
        private PIS.Train.RealTime.StationDataStructureType StationDataStructureField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string StationCode
        {
            get
            {
                return this.StationCodeField;
            }
            set
            {
                this.StationCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public PIS.Train.RealTime.StationDataStructureType StationDataStructure
        {
            get
            {
                return this.StationDataStructureField;
            }
            set
            {
                this.StationDataStructureField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StationDataStructureType", Namespace="http://alstom.com/pacis/pis/schema/realtimecommon/")]
    public partial class StationDataStructureType : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private PIS.Train.RealTime.ActionTypeEnum StationConnectionListActionField;
        
        private PIS.Train.RealTime.ListOfConnectionEntryType StationConnectionListField;
        
        private PIS.Train.RealTime.ActionTypeEnum StationDelayActionField;
        
        private PIS.Train.RealTime.DelayType StationDelayField;
        
        private PIS.Train.RealTime.ActionTypeEnum StationPlatformActionField;
        
        private PIS.Train.RealTime.PlatformType StationPlatformField;
        
        private PIS.Train.RealTime.ActionTypeEnum StationWeatherActionField;
        
        private PIS.Train.RealTime.WeatherType StationWeatherField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public PIS.Train.RealTime.ActionTypeEnum StationConnectionListAction
        {
            get
            {
                return this.StationConnectionListActionField;
            }
            set
            {
                this.StationConnectionListActionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public PIS.Train.RealTime.ListOfConnectionEntryType StationConnectionList
        {
            get
            {
                return this.StationConnectionListField;
            }
            set
            {
                this.StationConnectionListField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public PIS.Train.RealTime.ActionTypeEnum StationDelayAction
        {
            get
            {
                return this.StationDelayActionField;
            }
            set
            {
                this.StationDelayActionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public PIS.Train.RealTime.DelayType StationDelay
        {
            get
            {
                return this.StationDelayField;
            }
            set
            {
                this.StationDelayField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public PIS.Train.RealTime.ActionTypeEnum StationPlatformAction
        {
            get
            {
                return this.StationPlatformActionField;
            }
            set
            {
                this.StationPlatformActionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public PIS.Train.RealTime.PlatformType StationPlatform
        {
            get
            {
                return this.StationPlatformField;
            }
            set
            {
                this.StationPlatformField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public PIS.Train.RealTime.ActionTypeEnum StationWeatherAction
        {
            get
            {
                return this.StationWeatherActionField;
            }
            set
            {
                this.StationWeatherActionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public PIS.Train.RealTime.WeatherType StationWeather
        {
            get
            {
                return this.StationWeatherField;
            }
            set
            {
                this.StationWeatherField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PlatformType", Namespace="http://alstom.com/pacis/pis/schema/realtimecommon/")]
    public partial class PlatformType : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private uint AgeField;
        
        private string PlatformField;
        
        private string TrackField;
        
        private int TrackCodeField;
        
        private string ExitSideField;
        
        private int ExitSideCodeField;
        
        private string PlatformIssueDescriptionField;
        
        private int PlatformIssueDescriptionCodeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public uint Age
        {
            get
            {
                return this.AgeField;
            }
            set
            {
                this.AgeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Platform
        {
            get
            {
                return this.PlatformField;
            }
            set
            {
                this.PlatformField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Track
        {
            get
            {
                return this.TrackField;
            }
            set
            {
                this.TrackField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TrackCode
        {
            get
            {
                return this.TrackCodeField;
            }
            set
            {
                this.TrackCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string ExitSide
        {
            get
            {
                return this.ExitSideField;
            }
            set
            {
                this.ExitSideField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int ExitSideCode
        {
            get
            {
                return this.ExitSideCodeField;
            }
            set
            {
                this.ExitSideCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string PlatformIssueDescription
        {
            get
            {
                return this.PlatformIssueDescriptionField;
            }
            set
            {
                this.PlatformIssueDescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public int PlatformIssueDescriptionCode
        {
            get
            {
                return this.PlatformIssueDescriptionCodeField;
            }
            set
            {
                this.PlatformIssueDescriptionCodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ListOfConnectionEntryType", Namespace="http://alstom.com/pacis/pis/schema/realtimecommon/", ItemName="ConnectionEntry")]
    public class ListOfConnectionEntryType : System.Collections.Generic.List<PIS.Train.RealTime.ConnectionEntryType>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConnectionEntryType", Namespace="http://alstom.com/pacis/pis/schema/realtimecommon/")]
    public partial class ConnectionEntryType : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string UniqueConnectionIDField;
        
        private PIS.Train.RealTime.ActionTypeEnum ConnectionActionField;
        
        private PIS.Train.RealTime.ConnectionType ConnectionField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string UniqueConnectionID
        {
            get
            {
                return this.UniqueConnectionIDField;
            }
            set
            {
                this.UniqueConnectionIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public PIS.Train.RealTime.ActionTypeEnum ConnectionAction
        {
            get
            {
                return this.ConnectionActionField;
            }
            set
            {
                this.ConnectionActionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public PIS.Train.RealTime.ConnectionType Connection
        {
            get
            {
                return this.ConnectionField;
            }
            set
            {
                this.ConnectionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConnectionType", Namespace="http://alstom.com/pacis/pis/schema/realtimecommon/")]
    public partial class ConnectionType : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private uint AgeField;
        
        private string OperatorField;
        
        private int OperatorCodeField;
        
        private string CommercialNumberField;
        
        private string ModelTypeField;
        
        private int ModelTypeCodeField;
        
        private string LineField;
        
        private int LineCodeField;
        
        private string DepartureTimeField;
        
        private string NextDepartureTimeField;
        
        private string DepartureFrequencyField;
        
        private string PlatformField;
        
        private string DelayField;
        
        private string DestinationLabelField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public uint Age
        {
            get
            {
                return this.AgeField;
            }
            set
            {
                this.AgeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Operator
        {
            get
            {
                return this.OperatorField;
            }
            set
            {
                this.OperatorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OperatorCode
        {
            get
            {
                return this.OperatorCodeField;
            }
            set
            {
                this.OperatorCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string CommercialNumber
        {
            get
            {
                return this.CommercialNumberField;
            }
            set
            {
                this.CommercialNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string ModelType
        {
            get
            {
                return this.ModelTypeField;
            }
            set
            {
                this.ModelTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int ModelTypeCode
        {
            get
            {
                return this.ModelTypeCodeField;
            }
            set
            {
                this.ModelTypeCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Line
        {
            get
            {
                return this.LineField;
            }
            set
            {
                this.LineField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public int LineCode
        {
            get
            {
                return this.LineCodeField;
            }
            set
            {
                this.LineCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string DepartureTime
        {
            get
            {
                return this.DepartureTimeField;
            }
            set
            {
                this.DepartureTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string NextDepartureTime
        {
            get
            {
                return this.NextDepartureTimeField;
            }
            set
            {
                this.NextDepartureTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string DepartureFrequency
        {
            get
            {
                return this.DepartureFrequencyField;
            }
            set
            {
                this.DepartureFrequencyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string Platform
        {
            get
            {
                return this.PlatformField;
            }
            set
            {
                this.PlatformField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string Delay
        {
            get
            {
                return this.DelayField;
            }
            set
            {
                this.DelayField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string DestinationLabel
        {
            get
            {
                return this.DestinationLabelField;
            }
            set
            {
                this.DestinationLabelField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://alstom.com/pacis/pis/train/realtime/", ConfigurationName="PIS.Train.RealTime.IRealTimeTrainService")]
    public interface IRealTimeTrainService
    {
        
        // CODEGEN : La génération du contrat de message depuis l’espace de noms de wrapper (http://alstom.com/pacis/pis/schema/train/realtime/) du message SetMissionRealTimeRequest ne correspond pas à la valeur par défaut (http://alstom.com/pacis/pis/train/realtime/)
        [System.ServiceModel.OperationContractAttribute(Action="http://alstom.com/pacis/pis/train/realtime/SetMissionRealTime", ReplyAction="*")]
        PIS.Train.RealTime.SetMissionRealTimeResponse SetMissionRealTime(PIS.Train.RealTime.SetMissionRealTimeRequest request);
        
        // CODEGEN : La génération du contrat de message depuis l’espace de noms de wrapper (http://alstom.com/pacis/pis/schema/train/realtime/) du message SetStationRealTimeRequest ne correspond pas à la valeur par défaut (http://alstom.com/pacis/pis/train/realtime/)
        [System.ServiceModel.OperationContractAttribute(Action="http://alstom.com/pacis/pis/train/realtime/SetStationRealTime", ReplyAction="*")]
        PIS.Train.RealTime.SetStationRealTimeResponse SetStationRealTime(PIS.Train.RealTime.SetStationRealTimeRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MissionDataRequest", WrapperNamespace="http://alstom.com/pacis/pis/schema/train/realtime/", IsWrapped=true)]
    public partial class SetMissionRealTimeRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://alstom.com/pacis/pis/schema/realtimecommon/", Order=0)]
        public string MissionID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://alstom.com/pacis/pis/schema/realtimecommon/", Order=1)]
        public PIS.Train.RealTime.ActionTypeEnum MissionDelayAction;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://alstom.com/pacis/pis/schema/realtimecommon/", Order=2)]
        public PIS.Train.RealTime.DelayType MissionDelay;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://alstom.com/pacis/pis/schema/realtimecommon/", Order=3)]
        public PIS.Train.RealTime.ActionTypeEnum MissionWeatherAction;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://alstom.com/pacis/pis/schema/realtimecommon/", Order=4)]
        public PIS.Train.RealTime.WeatherType MissionWeather;
        
        public SetMissionRealTimeRequest()
        {
        }
        
        public SetMissionRealTimeRequest(string MissionID, PIS.Train.RealTime.ActionTypeEnum MissionDelayAction, PIS.Train.RealTime.DelayType MissionDelay, PIS.Train.RealTime.ActionTypeEnum MissionWeatherAction, PIS.Train.RealTime.WeatherType MissionWeather)
        {
            this.MissionID = MissionID;
            this.MissionDelayAction = MissionDelayAction;
            this.MissionDelay = MissionDelay;
            this.MissionWeatherAction = MissionWeatherAction;
            this.MissionWeather = MissionWeather;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Response", WrapperNamespace="http://alstom.com/pacis/pis/schema/train/realtime/", IsWrapped=true)]
    public partial class SetMissionRealTimeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://alstom.com/pacis/pis/schema/realtimecommon/", Order=0)]
        public PIS.Train.RealTime.ListOfResultType ResultList;
        
        public SetMissionRealTimeResponse()
        {
        }
        
        public SetMissionRealTimeResponse(PIS.Train.RealTime.ListOfResultType ResultList)
        {
            this.ResultList = ResultList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="StationDataRequest", WrapperNamespace="http://alstom.com/pacis/pis/schema/train/realtime/", IsWrapped=true)]
    public partial class SetStationRealTimeRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://alstom.com/pacis/pis/schema/realtimecommon/", Order=0)]
        public string MissionID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://alstom.com/pacis/pis/schema/realtimecommon/", Order=1)]
        public PIS.Train.RealTime.ListOfStationDataType StationDataList;
        
        public SetStationRealTimeRequest()
        {
        }
        
        public SetStationRealTimeRequest(string MissionID, PIS.Train.RealTime.ListOfStationDataType StationDataList)
        {
            this.MissionID = MissionID;
            this.StationDataList = StationDataList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Response", WrapperNamespace="http://alstom.com/pacis/pis/schema/train/realtime/", IsWrapped=true)]
    public partial class SetStationRealTimeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://alstom.com/pacis/pis/schema/realtimecommon/", Order=0)]
        public PIS.Train.RealTime.ListOfResultType ResultList;
        
        public SetStationRealTimeResponse()
        {
        }
        
        public SetStationRealTimeResponse(PIS.Train.RealTime.ListOfResultType ResultList)
        {
            this.ResultList = ResultList;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IRealTimeTrainServiceChannel : PIS.Train.RealTime.IRealTimeTrainService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class RealTimeTrainServiceClient : System.ServiceModel.ClientBase<PIS.Train.RealTime.IRealTimeTrainService>, PIS.Train.RealTime.IRealTimeTrainService
    {
        
        public RealTimeTrainServiceClient()
        {
        }
        
        public RealTimeTrainServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public RealTimeTrainServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public RealTimeTrainServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public RealTimeTrainServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PIS.Train.RealTime.SetMissionRealTimeResponse PIS.Train.RealTime.IRealTimeTrainService.SetMissionRealTime(PIS.Train.RealTime.SetMissionRealTimeRequest request)
        {
            return base.Channel.SetMissionRealTime(request);
        }
        
        public PIS.Train.RealTime.ListOfResultType SetMissionRealTime(string MissionID, PIS.Train.RealTime.ActionTypeEnum MissionDelayAction, PIS.Train.RealTime.DelayType MissionDelay, PIS.Train.RealTime.ActionTypeEnum MissionWeatherAction, PIS.Train.RealTime.WeatherType MissionWeather)
        {
            PIS.Train.RealTime.SetMissionRealTimeRequest inValue = new PIS.Train.RealTime.SetMissionRealTimeRequest();
            inValue.MissionID = MissionID;
            inValue.MissionDelayAction = MissionDelayAction;
            inValue.MissionDelay = MissionDelay;
            inValue.MissionWeatherAction = MissionWeatherAction;
            inValue.MissionWeather = MissionWeather;
            PIS.Train.RealTime.SetMissionRealTimeResponse retVal = ((PIS.Train.RealTime.IRealTimeTrainService)(this)).SetMissionRealTime(inValue);
            return retVal.ResultList;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PIS.Train.RealTime.SetStationRealTimeResponse PIS.Train.RealTime.IRealTimeTrainService.SetStationRealTime(PIS.Train.RealTime.SetStationRealTimeRequest request)
        {
            return base.Channel.SetStationRealTime(request);
        }
        
        public PIS.Train.RealTime.ListOfResultType SetStationRealTime(string MissionID, PIS.Train.RealTime.ListOfStationDataType StationDataList)
        {
            PIS.Train.RealTime.SetStationRealTimeRequest inValue = new PIS.Train.RealTime.SetStationRealTimeRequest();
            inValue.MissionID = MissionID;
            inValue.StationDataList = StationDataList;
            PIS.Train.RealTime.SetStationRealTimeResponse retVal = ((PIS.Train.RealTime.IRealTimeTrainService)(this)).SetStationRealTime(inValue);
            return retVal.ResultList;
        }
    }
}
